"""Claim epistemics: the scope ladder, negative-evidence discipline, and coverage.

Three pure rule engines that decide what the evidence actually defends:

* :mod:`~research_harness.claims.strength` computes the maximum defensible wording from
  accepted evidence and coverage. Model confidence is not an input (Product P6).
* :mod:`~research_harness.claims.negative_evidence` keeps the five absence states distinct
  and guards the audited road from `not_reported` to `absent` (Product 42.F).
* :mod:`~research_harness.claims.coverage` measures the discovery funnel, estimates
  overturn risk, and refuses absence claims the search record cannot support.

:mod:`~research_harness.claims.service` is the researcher-facing surface: it creates claims,
edits their evidence relations, runs the audit against accepted state, and turns an override
into a visible Decision (ROADMAP 7.1, 7.5).

:mod:`~research_harness.claims.audit` puts them together as the claim audit: the ceiling
the evidence defends, the independence and coverage doubts behind it, the relations it
proposes reclassifying, and the counter-evidence it went looking for. The Skeptic and the
Claim Auditor are consulted afterwards and may only narrow the result (ROADMAP 7.4).

    from research_harness.claims import StrengthInput, assess_strength

    assessment = assess_strength(StrengthInput.from_claim(claim, evidence_by_id))
    assessment.allowed, assessment.wording, assessment.reasons
"""

from __future__ import annotations

from research_harness.claims.audit import (
    AUDIT_DECISION_FIELDS,
    DEFAULT_COUNTER_LIMIT,
    GATE_ORDER,
    SKEPTIC_SOURCE,
    ClaimAuditInput,
    ClaimAuditResult,
    CounterEvidenceFinder,
    ModelJudgement,
    ProposedRelationChange,
    RetrievalCandidate,
    apply_audit,
    apply_auditor,
    apply_cross_verification,
    apply_skeptic,
    audit_claim,
    audit_claim_locally,
    available_providers,
    build_auditor_request,
    build_skeptic_request,
    claim_payload,
    comparison_differences,
    coverage_state,
    evidence_payload,
    select_cross_verify_gate,
    to_assessment,
)
from research_harness.claims.coverage import (
    HIGH_UNRESOLVED_RATIO,
    LOW_EXAMINED_RATIO,
    LOW_MODERATE_EXAMINED_RATIO,
    MIN_EXAMINED_RATIO,
    MIN_INDEPENDENT_SOURCES,
    MODERATE_UNRESOLVED_RATIO,
    UNSAFE_ABSENCE_RISK,
    CoverageLedger,
    CoverageReport,
    CoverageUniverse,
    absence_permitted,
    build_coverage_report,
    compute_coverage,
    estimate_overturn_risk,
    incomplete_runs,
    matrix_cell_absence_guard,
    parse_cutoff,
    run_is_incomplete,
    searched_sources,
    uncompleted_sources,
)
from research_harness.claims.negative_evidence import (
    BROAD_EFFORT_REQUIREMENTS,
    PromotionCheck,
    SearchEffort,
    absence_wording,
    check_promotion,
    classify_absence,
    promote_absence,
)
from research_harness.claims.service import (
    AUDIT_EVENTS,
    CLAIM_EVENTS,
    INITIAL_ALLOWED_STRENGTH,
    RELATION_EVENT,
    ClaimService,
    ClaimView,
    next_decision_id,
)
from research_harness.claims.strength import (
    ABSENCE_PHRASE,
    AUTHOR_ORIGINS,
    CONTRADICTING_RELATIONS,
    CONTRADICTION_TOLERANCE_DIVISOR,
    FIELD_WORDING,
    INDIVIDUAL_WORDING,
    L2_MIN_EXAMINED_RATIO,
    L2_MIN_INDEPENDENT_WORKS,
    L3_ACCEPTABLE_OVERTURN_RISK,
    L3_MAX_UNRESOLVED_RATIO,
    L3_MIN_EXAMINED_RATIO,
    L3_MIN_INDEPENDENT_WORKS,
    LEVEL_REQUIREMENTS,
    MAJORITY_RATIO,
    MAJORITY_WORDING,
    MIN_SUPPORT,
    OBSERVED_SUBSET_WORDING,
    QUALIFYING_RELATIONS,
    SEVERAL_WORDING,
    SUPPORT_WEIGHTS,
    SUPPORTING_RELATIONS,
    UNIVERSAL_WORDING,
    EvidenceSummary,
    LevelRequirement,
    StrengthAssessment,
    StrengthFacts,
    StrengthInput,
    assess_strength,
    build_facts,
    summarize,
    wording_for,
)

__all__ = [
    "ABSENCE_PHRASE",
    "AUDIT_DECISION_FIELDS",
    "AUDIT_EVENTS",
    "AUTHOR_ORIGINS",
    "BROAD_EFFORT_REQUIREMENTS",
    "CLAIM_EVENTS",
    "CONTRADICTING_RELATIONS",
    "CONTRADICTION_TOLERANCE_DIVISOR",
    "DEFAULT_COUNTER_LIMIT",
    "FIELD_WORDING",
    "GATE_ORDER",
    "HIGH_UNRESOLVED_RATIO",
    "INDIVIDUAL_WORDING",
    "INITIAL_ALLOWED_STRENGTH",
    "L2_MIN_EXAMINED_RATIO",
    "L2_MIN_INDEPENDENT_WORKS",
    "L3_ACCEPTABLE_OVERTURN_RISK",
    "L3_MAX_UNRESOLVED_RATIO",
    "L3_MIN_EXAMINED_RATIO",
    "L3_MIN_INDEPENDENT_WORKS",
    "LEVEL_REQUIREMENTS",
    "LOW_EXAMINED_RATIO",
    "LOW_MODERATE_EXAMINED_RATIO",
    "MAJORITY_RATIO",
    "MAJORITY_WORDING",
    "MIN_EXAMINED_RATIO",
    "MIN_INDEPENDENT_SOURCES",
    "MIN_SUPPORT",
    "MODERATE_UNRESOLVED_RATIO",
    "OBSERVED_SUBSET_WORDING",
    "QUALIFYING_RELATIONS",
    "RELATION_EVENT",
    "SEVERAL_WORDING",
    "SKEPTIC_SOURCE",
    "SUPPORTING_RELATIONS",
    "SUPPORT_WEIGHTS",
    "UNIVERSAL_WORDING",
    "UNSAFE_ABSENCE_RISK",
    "ClaimAuditInput",
    "ClaimAuditResult",
    "ClaimService",
    "ClaimView",
    "CounterEvidenceFinder",
    "CoverageLedger",
    "CoverageReport",
    "CoverageUniverse",
    "EvidenceSummary",
    "LevelRequirement",
    "ModelJudgement",
    "PromotionCheck",
    "ProposedRelationChange",
    "RetrievalCandidate",
    "SearchEffort",
    "StrengthAssessment",
    "StrengthFacts",
    "StrengthInput",
    "absence_permitted",
    "absence_wording",
    "apply_audit",
    "apply_auditor",
    "apply_cross_verification",
    "apply_skeptic",
    "assess_strength",
    "audit_claim",
    "audit_claim_locally",
    "available_providers",
    "build_auditor_request",
    "build_coverage_report",
    "build_facts",
    "build_skeptic_request",
    "check_promotion",
    "claim_payload",
    "classify_absence",
    "comparison_differences",
    "compute_coverage",
    "coverage_state",
    "estimate_overturn_risk",
    "evidence_payload",
    "incomplete_runs",
    "matrix_cell_absence_guard",
    "next_decision_id",
    "parse_cutoff",
    "promote_absence",
    "run_is_incomplete",
    "searched_sources",
    "select_cross_verify_gate",
    "summarize",
    "to_assessment",
    "uncompleted_sources",
    "wording_for",
]
