"""The ResearchGraph projection: typed nodes and edges over canonical and durable state.

Everything here lives under `.research/graph/` and is disposable (ADR-001, ADR-006). The
graph makes `@E0482` resolvable, Claim ↔ Evidence ↔ Artifact traversable in both
directions, and a provenance path cheap; it never decides what is accepted. Model-proposed
edges stay `candidate` by construction, and the deep-link resolver answers from canonical
files, not from a row.
"""

from __future__ import annotations

from research_harness.graph.projectors import (
    ANCHOR_PREFIX,
    BLOCK_PREFIX,
    CANDIDATE_PREFIX,
    CITATION_PREFIX,
    FILE_PREFIX,
    PROJECT_PREFIX,
    CandidateProjector,
    ClaimProjector,
    CorpusProjector,
    DecisionProjector,
    DocumentProjector,
    EvidenceProjector,
    ManuscriptProjector,
    ProjectionContext,
    ProjectionUnit,
    Projector,
    ProjectProjector,
    QuestionProjector,
    SynthesisProjector,
    anchor_identity,
    block_identity,
    candidate_identity,
    citation_identity,
    claim_authority,
    default_projectors,
    evidence_authority,
    graph_identity,
    manuscript_file_identity,
    project_all,
    project_identity,
)
from research_harness.graph.queries import (
    DEFAULT_LIMIT,
    MAX_HOPS,
    Direction,
    EdgeRecord,
    GraphFilter,
    Neighbour,
    NodeRecord,
    ProvenancePath,
    ProvenanceStep,
    SearchHit,
)
from research_harness.graph.rebuild import (
    GraphReport,
    GraphStatus,
    dump_graph,
    event_cursor,
    graph_status,
    rebuild_graph,
    update_graph,
)
from research_harness.graph.resolver import ResolvedTarget, resolve_deep_link
from research_harness.graph.schema import (
    CHECKPOINTS,
    EDGES,
    FINGERPRINTS,
    GRAPH_SCHEMA_VERSION,
    NODES,
    NODES_FTS,
    create_all,
    create_engine_for,
    drop_all,
    graph_database_path,
    graph_dir,
)
from research_harness.graph.service import ResearchGraph

__all__ = [
    "ANCHOR_PREFIX",
    "BLOCK_PREFIX",
    "CANDIDATE_PREFIX",
    "CHECKPOINTS",
    "CITATION_PREFIX",
    "DEFAULT_LIMIT",
    "EDGES",
    "FILE_PREFIX",
    "FINGERPRINTS",
    "GRAPH_SCHEMA_VERSION",
    "MAX_HOPS",
    "NODES",
    "NODES_FTS",
    "PROJECT_PREFIX",
    "CandidateProjector",
    "ClaimProjector",
    "CorpusProjector",
    "DecisionProjector",
    "Direction",
    "DocumentProjector",
    "EdgeRecord",
    "EvidenceProjector",
    "GraphFilter",
    "GraphReport",
    "GraphStatus",
    "ManuscriptProjector",
    "Neighbour",
    "NodeRecord",
    "ProjectProjector",
    "ProjectionContext",
    "ProjectionUnit",
    "Projector",
    "ProvenancePath",
    "ProvenanceStep",
    "QuestionProjector",
    "ResearchGraph",
    "ResolvedTarget",
    "SearchHit",
    "SynthesisProjector",
    "anchor_identity",
    "block_identity",
    "candidate_identity",
    "citation_identity",
    "claim_authority",
    "create_all",
    "create_engine_for",
    "default_projectors",
    "drop_all",
    "dump_graph",
    "event_cursor",
    "evidence_authority",
    "graph_database_path",
    "graph_dir",
    "graph_identity",
    "graph_status",
    "manuscript_file_identity",
    "project_all",
    "project_identity",
    "rebuild_graph",
    "resolve_deep_link",
    "update_graph",
]
