"""Document IR over synthetic PDFs with known pages, tables, and structure (Task 2.3, 2.4).

Fixtures are generated by `tests.fixtures.make_synthetic_paper`, which also records the
ground truth asserted here, so no publisher PDF is needed to test the parser.
"""

from __future__ import annotations

import hashlib
import re
from datetime import UTC, datetime
from pathlib import Path

import pymupdf
import pytest

from research_harness.domain.document import DocumentBlock, ParsedDocument
from research_harness.domain.enums import DocumentBlockKind
from research_harness.domain.ids import ArtifactId, VersionId, WorkId
from research_harness.parsing.anchors import build_anchor, resolve_anchor, validate_anchor
from research_harness.parsing.base import (
    ParseError,
    ParseTarget,
    UnsupportedArtifactError,
    diagnostics_summary,
    document_fingerprint,
    select_parser,
)
from research_harness.parsing.pymupdf_parser import PyMuPdfParser
from research_harness.parsing.tables import cell_span, cell_text, column_headers
from research_harness.parsing.text import text_sha256
from tests.fixtures.make_synthetic_paper import (
    GROUND_TRUTH,
    build_single_column_paper,
    build_two_column_paper,
    render,
)

SINGLE = GROUND_TRUTH["synthetic_research_paper"]
TWO_COLUMN = GROUND_TRUTH["synthetic_two_column_paper"]
FIXED_CLOCK = datetime(2024, 1, 1, tzinfo=UTC)

TEXT_KINDS = frozenset(DocumentBlockKind) - {DocumentBlockKind.TABLE}


def make_target(path: Path, *, mime_type: str = "application/pdf") -> ParseTarget:
    digest = hashlib.sha256(path.read_bytes()).hexdigest()
    return ParseTarget(
        work=WorkId("W0001"),
        version=VersionId("V0001-1"),
        artifact=ArtifactId("A0001-1"),
        file_hash=f"sha256:{digest}",
        path=path,
        mime_type=mime_type,
    )


def blocks_containing(doc: ParsedDocument, needle: str) -> list[DocumentBlock]:
    return [block for block in doc.blocks if needle in block.text]


def one_block_containing(doc: ParsedDocument, needle: str) -> DocumentBlock:
    found = blocks_containing(doc, needle)
    assert found, f"no block contains {needle!r}"
    return found[0]


@pytest.fixture(scope="module")
def parser() -> PyMuPdfParser:
    return PyMuPdfParser()


@pytest.fixture(scope="module")
def paper(parser: PyMuPdfParser) -> ParsedDocument:
    return parser.parse(make_target(SINGLE["path"]))


@pytest.fixture(scope="module")
def two_column(parser: PyMuPdfParser) -> ParsedDocument:
    return parser.parse(make_target(TWO_COLUMN["path"]))


# -- structure -----------------------------------------------------------------------


def test_parser_reports_its_identity_and_page_count(paper: ParsedDocument) -> None:
    assert paper.parser_name == "pymupdf"
    assert paper.parser_version == PyMuPdfParser.version == "1.1"
    assert paper.page_count == SINGLE["page_count"]
    assert paper.artifact == ArtifactId("A0001-1")


def test_a_well_formed_paper_reports_no_decoding_problems() -> None:
    """Hardening must not manufacture diagnostics: these fixtures have nothing wrong with them."""
    parser = PyMuPdfParser()
    for expected in (SINGLE, TWO_COLUMN):
        parsed = parser.parse(make_target(expected["path"]))
        diagnostics = parser.last_diagnostics
        assert diagnostics is not None and diagnostics.is_clean, expected["path"].name
        assert diagnostics_summary(parsed) == "no undecodable blocks"


def test_no_block_of_a_well_formed_paper_runs_words_together(
    paper: ParsedDocument, two_column: ParsedDocument
) -> None:
    """Space reconstruction is a repair, not a rewrite: these papers drew their own spaces."""
    run_on = re.compile(r"[A-Za-z]{26,}")
    for parsed in (paper, two_column):
        assert [block.id for block in parsed.blocks if run_on.search(block.text)] == []


def test_every_block_carries_a_page_and_a_bbox_inside_that_page(paper: ParsedDocument) -> None:
    page_rect = (0.0, 0.0, 612.0, 792.0)
    for block in paper.blocks:
        assert 1 <= block.page <= paper.page_count
        assert block.bbox is not None, f"{block.id} has no geometry"
        x0, y0, x1, y1 = block.bbox.as_tuple()
        assert page_rect[0] <= x0 <= x1 <= page_rect[2]
        assert page_rect[1] <= y0 <= y1 <= page_rect[3]


def test_blocks_are_numbered_sequentially_in_reading_order(paper: ParsedDocument) -> None:
    assert [block.order for block in paper.blocks] == list(range(len(paper.blocks)))
    assert [str(block.id) for block in paper.blocks][:3] == ["B0001", "B0002", "B0003"]


def test_every_block_hashes_its_own_text(paper: ParsedDocument) -> None:
    for block in paper.blocks:
        assert block.text_hash == text_sha256(block.text)


def test_known_strings_appear_on_their_known_pages(paper: ParsedDocument) -> None:
    for needle, page in SINGLE["strings_on_pages"].items():
        pages = {block.page for block in blocks_containing(paper, needle)}
        assert pages == {page}, f"{needle!r} found on {pages}, expected page {page}"


def test_headings_become_section_blocks(paper: ParsedDocument) -> None:
    headings = [block.text for block in paper.blocks if block.kind is DocumentBlockKind.SECTION]
    assert headings == list(SINGLE["headings"])


def test_section_path_records_the_enclosing_headings(paper: ParsedDocument) -> None:
    probe = SINGLE["section_path_probe"]
    block = one_block_containing(paper, probe["contains"])
    assert block.kind is DocumentBlockKind.PARAGRAPH
    assert block.section_path == probe["section_path"]


def test_equations_captions_and_footnotes_are_classified(paper: ParsedDocument) -> None:
    equation = one_block_containing(paper, SINGLE["equation"]["contains"])
    assert equation.kind is DocumentBlockKind.EQUATION
    assert equation.page == SINGLE["equation"]["page"]

    caption = one_block_containing(paper, SINGLE["figure_caption"]["text"])
    assert caption.kind is DocumentBlockKind.FIGURE_CAPTION
    assert caption.page == SINGLE["figure_caption"]["page"]
    assert caption.caption == SINGLE["figure_caption"]["text"]

    footnote = one_block_containing(paper, SINGLE["footnote"]["contains"])
    assert footnote.kind is DocumentBlockKind.FOOTNOTE
    assert footnote.page == SINGLE["footnote"]["page"]


def test_an_orphaned_table_caption_keeps_its_own_kind(
    tmp_path: Path, parser: PyMuPdfParser
) -> None:
    """A `Table N:` line with no table nearby is a table caption, never a figure's."""
    document = pymupdf.open()
    page = document.new_page()
    page.insert_text((72, 100), "Table 9: Hyperparameters used for every run.", fontsize=9)
    page.insert_text((72, 140), "Figure 4: The pipeline, end to end.", fontsize=9)
    page.insert_text((72, 180), "The table itself did not survive the export.", fontsize=9)
    path = tmp_path / "orphan-caption.pdf"
    document.save(path)
    document.close()

    parsed = parser.parse(make_target(path))

    table_caption = one_block_containing(parsed, "Table 9:")
    assert table_caption.kind is DocumentBlockKind.TABLE_CAPTION
    assert table_caption.caption == "Table 9: Hyperparameters used for every run."
    assert one_block_containing(parsed, "Figure 4:").kind is DocumentBlockKind.FIGURE_CAPTION


def test_the_references_section_yields_one_block_per_entry(paper: ParsedDocument) -> None:
    references = [block for block in paper.blocks if block.kind is DocumentBlockKind.REFERENCE]
    assert len(references) == SINGLE["reference_count"]
    assert tuple(block.reference_key for block in references) == SINGLE["reference_keys"]
    assert all(block.reference_raw == block.text for block in references)
    assert "Networking, pages 11-24, 2023." in references[0].text


# -- tables --------------------------------------------------------------------------


def test_table_cells_keep_their_row_and_column_coordinates(paper: ParsedDocument) -> None:
    expected = SINGLE["table"]
    tables = [block for block in paper.blocks if block.kind is DocumentBlockKind.TABLE]
    assert len(tables) == 1
    table = tables[0]
    assert table.page == expected["page"]
    assert table.caption == expected["caption"]
    assert {cell.row for cell in table.cells} == set(range(expected["row_count"]))
    assert {cell.col for cell in table.cells} == set(range(expected["col_count"]))
    for (row, col), text in expected["cells"].items():
        assert cell_text(table, row, col) == text
    assert column_headers(table) == ("Model", "Dataset", "F1", "Precision")
    assert all(cell.bbox is not None for cell in table.cells)


def test_cell_span_locates_a_measured_value_in_the_flattened_table(
    paper: ParsedDocument,
) -> None:
    numeric = SINGLE["table"]["numeric_cell"]
    table = next(block for block in paper.blocks if block.kind is DocumentBlockKind.TABLE)
    start, end = cell_span(table, numeric["row"], numeric["col"])
    assert table.text[start:end] == numeric["text"]
    assert 0 <= start < end <= len(table.text)


def test_paragraph_blocks_never_duplicate_table_content(paper: ParsedDocument) -> None:
    for block in paper.blocks:
        if block.kind in TEXT_KINDS:
            assert "TrafficLM | CICIDS2017" not in block.text


# -- two-column layout ---------------------------------------------------------------


def test_two_column_pages_read_left_column_before_right(two_column: ParsedDocument) -> None:
    expected = TWO_COLUMN["reading_order"]
    first = one_block_containing(two_column, expected["first"])
    then = one_block_containing(two_column, expected["then"])
    assert first.page == then.page == expected["page"]
    assert first.order < then.order
    assert first.bbox is not None and then.bbox is not None
    assert first.bbox.x0 < then.bbox.x0


def test_two_column_headings_are_found_in_both_columns(two_column: ParsedDocument) -> None:
    headings = {
        block.text for block in two_column.blocks if block.kind is DocumentBlockKind.SECTION
    }
    assert set(TWO_COLUMN["headings_by_column"].values()) <= headings


def test_two_column_tables_keep_their_cells_and_captions(two_column: ParsedDocument) -> None:
    tables = [block for block in two_column.blocks if block.kind is DocumentBlockKind.TABLE]
    assert len(tables) == len(TWO_COLUMN["tables"])
    for table, expected in zip(tables, TWO_COLUMN["tables"], strict=True):
        assert table.page == expected["page"]
        assert table.caption == expected["caption"]
        for (row, col), text in expected["cells"].items():
            assert cell_text(table, row, col) == text


def test_two_column_pages_and_references(two_column: ParsedDocument) -> None:
    assert two_column.page_count == TWO_COLUMN["page_count"]
    references = [block for block in two_column.blocks if block.kind is DocumentBlockKind.REFERENCE]
    assert len(references) == TWO_COLUMN["reference_count"]
    for needle, page in TWO_COLUMN["strings_on_pages"].items():
        assert {block.page for block in blocks_containing(two_column, needle)} == {page}


# -- determinism and failure ---------------------------------------------------------


def test_parsing_the_same_bytes_twice_is_identical() -> None:
    target = make_target(SINGLE["path"])
    first = PyMuPdfParser(clock=lambda: FIXED_CLOCK).parse(target)
    second = PyMuPdfParser(clock=lambda: FIXED_CLOCK).parse(target)
    assert first.model_dump() == second.model_dump()


def test_content_fingerprint_ignores_parse_timestamps(paper: ParsedDocument) -> None:
    again = PyMuPdfParser().parse(make_target(SINGLE["path"]))
    assert again.parsed_at != paper.parsed_at or again.blocks == paper.blocks
    assert document_fingerprint(again) == document_fingerprint(paper)


def test_regenerating_the_fixture_reproduces_the_same_document(tmp_path: Path) -> None:
    """The committed PDFs are exactly what the generator produces."""
    for build, source in (
        (build_single_column_paper, SINGLE["path"]),
        (build_two_column_paper, TWO_COLUMN["path"]),
    ):
        regenerated = tmp_path / source.name
        regenerated.write_bytes(render(build()))
        parser = PyMuPdfParser()
        assert document_fingerprint(parser.parse(make_target(regenerated))) == (
            document_fingerprint(parser.parse(make_target(source)))
        )


def test_a_corrupt_pdf_raises_parse_error_and_writes_nothing(
    tmp_path: Path, parser: PyMuPdfParser
) -> None:
    corrupt = tmp_path / "corrupt.pdf"
    corrupt.write_bytes(SINGLE["path"].read_bytes()[:900])
    before = sorted(path.name for path in tmp_path.iterdir())
    with pytest.raises(ParseError):
        parser.parse(make_target(corrupt))
    assert sorted(path.name for path in tmp_path.iterdir()) == before


def test_a_missing_file_raises_parse_error(tmp_path: Path, parser: PyMuPdfParser) -> None:
    absent = tmp_path / "nothing.pdf"
    absent.write_bytes(b"%PDF-1.7\n")
    target = make_target(absent)
    absent.unlink()
    with pytest.raises(ParseError, match="not found"):
        parser.parse(target)
    assert not list(tmp_path.iterdir())


def test_a_non_pdf_artifact_is_refused(parser: PyMuPdfParser) -> None:
    assert parser.supports("application/pdf; charset=binary")
    assert not parser.supports("text/html")
    with pytest.raises(UnsupportedArtifactError):
        parser.parse(make_target(SINGLE["path"], mime_type="text/html"))
    assert select_parser([parser], "application/pdf") is parser
    with pytest.raises(UnsupportedArtifactError):
        select_parser([parser], "text/html")


# -- anchors over a real parse -------------------------------------------------------


def test_an_anchor_built_on_a_table_cell_resolves_back_to_its_page_and_span(
    paper: ParsedDocument,
) -> None:
    expected = SINGLE["table"]["numeric_cell"]
    table = next(block for block in paper.blocks if block.kind is DocumentBlockKind.TABLE)
    start, end = cell_span(table, expected["row"], expected["col"])
    anchor = build_anchor(paper, table, start, end)
    assert validate_anchor(anchor, paper).is_valid
    span = resolve_anchor(anchor, paper)
    assert span.text == expected["text"]
    assert span.page == SINGLE["table"]["page"]
    assert span.bbox == table.bbox


def test_an_anchor_goes_stale_when_the_artifact_changes(
    paper: ParsedDocument, tmp_path: Path
) -> None:
    """One changed byte in the artifact invalidates the hash; nothing reattaches."""
    block = one_block_containing(paper, "10.1000/xyz123")
    offset = block.text.index("10.1000/xyz123")
    anchor = build_anchor(paper, block, offset, offset + len("10.1000/xyz123"))

    edited = tmp_path / "edited.pdf"
    original = SINGLE["path"].read_bytes()
    edited.write_bytes(original + b"\n%% one more byte\n")
    reparsed = PyMuPdfParser().parse(make_target(edited))

    result = validate_anchor(anchor, reparsed)
    assert not result.is_valid
    assert result.matched_block is None
    assert "artifact bytes changed" in result.reason
