/**
 * Generated by scripts/gen-types.mjs from the daemon snapshots. Do not edit by hand.
 *
 * Refresh with:
 *   uv run python web/scripts/export_backend_json.py   # re-export the snapshots
 *   pnpm gen:types                                     # regenerate this file
 */

/** Every capability this build of the daemon exposes. A typo is a compile error. */
export type CapabilityName =
  | "anchor.list"
  | "attachment.add"
  | "attachment.check_send"
  | "attachment.remove"
  | "attachment.resolve_identity"
  | "attachment.save_to_corpus"
  | "citation.verify"
  | "claim.audit"
  | "claim.create"
  | "claim.find_counterevidence"
  | "claim.find_support"
  | "claim.list"
  | "claim.override_strength"
  | "claim.relate"
  | "claim.supersede"
  | "claim.unrelate"
  | "claim.update_coverage"
  | "context.get"
  | "context.preview"
  | "corpus.ingest"
  | "corpus.screen"
  | "corpus.search"
  | "decision.accept"
  | "decision.list"
  | "decision.supersede"
  | "evidence.accept"
  | "evidence.extract"
  | "evidence.list"
  | "evidence.reject"
  | "evidence.verify"
  | "graph.autocomplete"
  | "graph.neighbors"
  | "graph.provenance"
  | "graph.query"
  | "graph.resolve"
  | "graph.status"
  | "manuscript.anchors"
  | "manuscript.apply_suggestion"
  | "manuscript.attach_claim"
  | "manuscript.audit"
  | "manuscript.build"
  | "manuscript.compile"
  | "manuscript.draft"
  | "manuscript.files"
  | "manuscript.read_file"
  | "manuscript.revalidate"
  | "manuscript.suggest"
  | "manuscript.synctex"
  | "manuscript.trace"
  | "manuscript.write_file"
  | "note.add"
  | "note.discard"
  | "note.promote"
  | "provider.cli.configure"
  | "provider.cli.remove"
  | "provider.cli.scan"
  | "provider.cli.test"
  | "provider.list"
  | "question.create"
  | "question.list"
  | "question.resolve"
  | "question.update"
  | "retrieval.resolve_source"
  | "retrieval.search"
  | "review.accept"
  | "review.accept_batch"
  | "review.candidate"
  | "review.defer"
  | "review.edit"
  | "review.inbox"
  | "review.qualify"
  | "review.reject"
  | "review.request_more"
  | "review.resolve_conflict"
  | "review.split"
  | "run.cancel"
  | "run.status"
  | "search_run.get"
  | "search_run.list"
  | "search_run.record"
  | "session.configure"
  | "session.create"
  | "session.get"
  | "session.list"
  | "session.promote"
  | "session.rename"
  | "session.retry"
  | "session.search"
  | "session.send"
  | "session.stop"
  | "session.summarize"
  | "state.index"
  | "state.rebuild"
  | "state.stale"
  | "synthesis.build_matrix"
  | "synthesis.compare"
  | "taxonomy.put"
  | "work.add_artifact"
  | "work.get"
  | "work.interrogate"
  | "work.list"
  | "work.parse"
  | "work.register"
  | "work.store_blocks"
  | "work.update_metadata";

export interface CapabilityMeta {
  /** What the call is allowed to touch: read, stage, mutate, or admin. */
  permission: 'read' | 'stage' | 'mutate' | 'admin';
  /** True when the call needs the researcher; the cockpit disables it for an agent host. */
  humanOnly: boolean;
  /** True when the call returns a run id and finishes in the background. */
  longRunning: boolean;
  summary: string;
  semantics: string;
}

export const CAPABILITIES: Record<CapabilityName, CapabilityMeta> = {
  "anchor.list": {
    permission: "read",
    humanOnly: false,
    longRunning: false,
    summary: "Every manuscript sentence bound to a Claim.",
    semantics: "reads canonical state; changes nothing",
  },
  "attachment.add": {
    permission: "mutate",
    humanOnly: true,
    longRunning: false,
    summary: "Attach a file to a session as working material.",
    semantics: "copies bytes into a session; creates no Work, Version, Artifact, or Evidence",
  },
  "attachment.check_send": {
    permission: "read",
    humanOnly: false,
    longRunning: false,
    summary: "Whether each attachment may go to the selected model, and why not.",
    semantics: "reads attachment records and provider capabilities; changes nothing",
  },
  "attachment.remove": {
    permission: "mutate",
    humanOnly: true,
    longRunning: false,
    summary: "Delete a session attachment, its bytes, and its previews.",
    semantics: "removes session-only working material; the corpus is not touched",
  },
  "attachment.resolve_identity": {
    permission: "read",
    humanOnly: false,
    longRunning: false,
    summary: "What one attachment would become in the corpus, without saving it.",
    semantics: "resolves corpus identity for a file; writes nothing",
  },
  "attachment.save_to_corpus": {
    permission: "mutate",
    humanOnly: true,
    longRunning: false,
    summary: "Promote a session attachment into the corpus under a resolved identity.",
    semantics: "creates or links Work/Version/Artifact identity and parses the file; accepts no Evidence or Claim",
  },
  "citation.verify": {
    permission: "read",
    humanOnly: false,
    longRunning: false,
    summary: "Check every manuscript citation key against the bibliography.",
    semantics: "reports missing or unused citation keys; changes nothing",
  },
  "claim.audit": {
    permission: "mutate",
    humanOnly: true,
    longRunning: false,
    summary: "Record what the evidence allows a Claim to say.",
    semantics: "writes the Claim's assessment: status, allowed strength, defensible wording",
  },
  "claim.create": {
    permission: "mutate",
    humanOnly: true,
    longRunning: false,
    summary: "Register a structured Claim.",
    semantics: "creates a Claim at its requested strength; the audit decides what it may say",
  },
  "claim.find_counterevidence": {
    permission: "read",
    humanOnly: false,
    longRunning: false,
    summary: "Retrieval proposals that might bear against a Claim.",
    semantics: "proposes places to look; creates no Evidence and no relation",
  },
  "claim.find_support": {
    permission: "read",
    humanOnly: false,
    longRunning: false,
    summary: "The evidence a Claim records, resolved, grouped by relation.",
    semantics: "reads claim-evidence relations; changes nothing",
  },
  "claim.list": {
    permission: "read",
    humanOnly: false,
    longRunning: false,
    summary: "Claim summaries, filtered by status, staleness, and type.",
    semantics: "reads canonical state; changes nothing",
  },
  "claim.override_strength": {
    permission: "mutate",
    humanOnly: true,
    longRunning: false,
    summary: "Apply an accepted epistemic override to a Claim.",
    semantics: "raises or lowers a Claim's allowed strength under a recorded Decision",
  },
  "claim.relate": {
    permission: "mutate",
    humanOnly: true,
    longRunning: false,
    summary: "Link one evidence object to a Claim under a relation and aspect.",
    semantics: "adds one claim-evidence edge; never rewrites the claim's assessment",
  },
  "claim.supersede": {
    permission: "mutate",
    humanOnly: true,
    longRunning: false,
    summary: "Retire a Claim, optionally naming the claim that replaces it.",
    semantics: "moves a Claim to superseded, which is terminal; human-only",
  },
  "claim.unrelate": {
    permission: "mutate",
    humanOnly: true,
    longRunning: false,
    summary: "Remove exactly one claim-evidence edge.",
    semantics: "drops one claim-evidence edge; the assessment is left as it was",
  },
  "claim.update_coverage": {
    permission: "mutate",
    humanOnly: true,
    longRunning: false,
    summary: "Record the search coverage a Claim's scope rests on.",
    semantics: "writes the deterministic discovery funnel onto a Claim; the audit reads it and no model contributes to it",
  },
  "context.get": {
    permission: "read",
    humanOnly: false,
    longRunning: false,
    summary: "Read the `Context used` receipt recorded for one past model call.",
    semantics: "reads a stored receipt of private working context; the receipt is a record of what a model was shown and carries no scientific authority",
  },
  "context.preview": {
    permission: "read",
    humanOnly: false,
    longRunning: false,
    summary: "Assemble the context a message would send, without sending it.",
    semantics: "reads what would be packed and what would be refused; sends nothing",
  },
  "corpus.ingest": {
    permission: "mutate",
    humanOnly: true,
    longRunning: false,
    summary: "Register a local file as an immutable Artifact of a Work.",
    semantics: "creates Work/Version/Artifact identity from a file; proposes no evidence",
  },
  "corpus.screen": {
    permission: "mutate",
    humanOnly: true,
    longRunning: false,
    summary: "Include or exclude one discovery candidate, with its reason.",
    semantics: "records a screening decision on a SearchRun; acquires no source",
  },
  "corpus.search": {
    permission: "mutate",
    humanOnly: true,
    longRunning: false,
    summary: "Search the configured external sources and record the run.",
    semantics: "reads external catalogues and writes nothing to them; records the SearchRun that makes the operation reproducible, and adds nothing to the corpus",
  },
  "decision.accept": {
    permission: "mutate",
    humanOnly: true,
    longRunning: false,
    summary: "Accept a proposed researcher Decision.",
    semantics: "moves a Decision to accepted; a researcher act (Product 38)",
  },
  "decision.list": {
    permission: "read",
    humanOnly: false,
    longRunning: false,
    summary: "Recorded researcher decisions, optionally for one Claim.",
    semantics: "reads canonical state; changes nothing",
  },
  "decision.supersede": {
    permission: "mutate",
    humanOnly: true,
    longRunning: false,
    summary: "Retire an accepted Decision, optionally naming its replacement.",
    semantics: "moves a Decision to superseded; the record of the choice stays",
  },
  "evidence.accept": {
    permission: "mutate",
    humanOnly: true,
    longRunning: false,
    summary: "Accept a reviewed candidate as canonical Evidence.",
    semantics: "creates accepted Evidence from a reviewed candidate; requires a human actor",
  },
  "evidence.extract": {
    permission: "stage",
    humanOnly: false,
    longRunning: true,
    summary: "Extract evidence for a Work's fields; the interrogation run, by field.",
    semantics: "stages evidence candidates under .research/staging; accepts nothing",
  },
  "evidence.list": {
    permission: "read",
    humanOnly: false,
    longRunning: false,
    summary: "Accepted evidence by work and status; staged proposals are not listed.",
    semantics: "reads canonical state; changes nothing",
  },
  "evidence.reject": {
    permission: "mutate",
    humanOnly: true,
    longRunning: false,
    summary: "Refuse a candidate and record why.",
    semantics: "records a refusal so the same proposal is recognised again; creates no Evidence",
  },
  "evidence.verify": {
    permission: "stage",
    humanOnly: false,
    longRunning: true,
    summary: "Re-read the source for staged candidates; returns a run id.",
    semantics: "writes verification verdicts onto staged candidates; accepts nothing",
  },
  "graph.autocomplete": {
    permission: "read",
    humanOnly: false,
    longRunning: false,
    summary: "Complete a partially typed reference for the composer.",
    semantics: "reads a disposable projection; changes no canonical object and grants no authority of its own",
  },
  "graph.neighbors": {
    permission: "read",
    humanOnly: false,
    longRunning: false,
    summary: "One- or two-hop neighbourhood of a node, in either direction.",
    semantics: "reads a disposable projection; changes no canonical object and grants no authority of its own",
  },
  "graph.provenance": {
    permission: "read",
    humanOnly: false,
    longRunning: false,
    summary: "Shortest path from a node to its source, e.g. Claim to Artifact anchor.",
    semantics: "reads a disposable projection; changes no canonical object and grants no authority of its own",
  },
  "graph.query": {
    permission: "read",
    humanOnly: false,
    longRunning: false,
    summary: "Nodes matching a structured kind/authority/visibility/link filter.",
    semantics: "reads a disposable projection; changes no canonical object and grants no authority of its own",
  },
  "graph.resolve": {
    permission: "read",
    humanOnly: false,
    longRunning: false,
    summary: "Resolve an `@` reference or `rh://` deep link against canonical state.",
    semantics: "reads a disposable projection; changes no canonical object and grants no authority of its own",
  },
  "graph.status": {
    permission: "read",
    humanOnly: false,
    longRunning: false,
    summary: "Whether the graph index exists, how big it is, and when it was built.",
    semantics: "reads a disposable projection; changes no canonical object and grants no authority of its own",
  },
  "manuscript.anchors": {
    permission: "read",
    humanOnly: false,
    longRunning: false,
    summary: "Every stored anchor, with its verdict against the manuscript on disk.",
    semantics: "reads anchors and computes their verdicts; records none of them",
  },
  "manuscript.apply_suggestion": {
    permission: "mutate",
    humanOnly: true,
    longRunning: false,
    summary: "Apply a reviewed candidate diff to the manuscript source.",
    semantics: "writes owned manuscript source from an audited candidate and records the source mutation; refuses a changed protected span, a failed audit, and a stale hash",
  },
  "manuscript.attach_claim": {
    permission: "mutate",
    humanOnly: true,
    longRunning: false,
    summary: "Bind a manuscript sentence to a Claim.",
    semantics: "creates the manuscript anchor that makes a sentence auditable (Product 30.1)",
  },
  "manuscript.audit": {
    permission: "read",
    humanOnly: false,
    longRunning: false,
    summary: "Audit the manuscript against the accepted research graph.",
    semantics: "reports findings; repairs nothing and writes nothing",
  },
  "manuscript.build": {
    permission: "read",
    humanOnly: false,
    longRunning: false,
    summary: "One build: compiler diagnostics and scientific audit findings.",
    semantics: "reads a recorded build and audits the manuscript; changes nothing",
  },
  "manuscript.compile": {
    permission: "mutate",
    humanOnly: true,
    longRunning: false,
    summary: "Run the configured local LaTeX engine once, bounded and confined.",
    semantics: "runs a local process over owned source and writes only disposable build outputs; no manuscript file is changed",
  },
  "manuscript.draft": {
    permission: "stage",
    humanOnly: false,
    longRunning: false,
    summary: "Draft a section from named accepted Claims, into staging.",
    semantics: "writes a draft candidate under .research/staging; the manuscript is untouched",
  },
  "manuscript.files": {
    permission: "read",
    humanOnly: false,
    longRunning: false,
    summary: "Every source file of the manuscript a researcher can open.",
    semantics: "reads owned manuscript source; changes nothing",
  },
  "manuscript.read_file": {
    permission: "read",
    humanOnly: false,
    longRunning: false,
    summary: "One manuscript file with the hash a later save must present.",
    semantics: "reads one owned source file; changes nothing",
  },
  "manuscript.revalidate": {
    permission: "mutate",
    humanOnly: true,
    longRunning: false,
    summary: "Re-find every stored anchor and record what the manuscript now says.",
    semantics: "records anchor relocation and staleness; a reworded sentence goes stale rather than being reattached, and it requires a human actor",
  },
  "manuscript.suggest": {
    permission: "stage",
    humanOnly: false,
    longRunning: false,
    summary: "Stage a model rewrite of one span as a reviewable candidate diff.",
    semantics: "writes a candidate under .research/staging with its protected-span, semantic, and Claim-wording verdicts; the manuscript is untouched",
  },
  "manuscript.synctex": {
    permission: "read",
    humanOnly: false,
    longRunning: false,
    summary: "Source-to-PDF and PDF-to-source navigation for one build.",
    semantics: "reads the compiler's SyncTeX map; changes nothing",
  },
  "manuscript.trace": {
    permission: "read",
    humanOnly: false,
    longRunning: false,
    summary: "One sentence, by file and line, down to its Claim and source spans.",
    semantics: "reads the traceability chain; changes nothing",
  },
  "manuscript.write_file": {
    permission: "mutate",
    humanOnly: true,
    longRunning: false,
    summary: "Save one manuscript file, refusing an outside change.",
    semantics: "writes the researcher's own manuscript source under a hash check; refuses when the file changed outside the harness",
  },
  "note.add": {
    permission: "mutate",
    humanOnly: true,
    longRunning: false,
    summary: "Capture a low-authority research note.",
    semantics: "creates a note that can never be cited as support until it is promoted",
  },
  "note.discard": {
    permission: "mutate",
    humanOnly: true,
    longRunning: false,
    summary: "Retire a captured note; discarded is terminal.",
    semantics: "ends a note's life; nothing downstream moves",
  },
  "note.promote": {
    permission: "mutate",
    humanOnly: true,
    longRunning: false,
    summary: "Record the research object a captured note became.",
    semantics: "raises a note's authority into a Claim, Question, or Decision; human-only",
  },
  "provider.cli.configure": {
    permission: "admin",
    humanOnly: true,
    longRunning: false,
    summary: "Add or update one subscription-backed CLI provider entry in research.yaml.",
    semantics: "changes provider configuration only; writes no research object and no event",
  },
  "provider.cli.remove": {
    permission: "admin",
    humanOnly: true,
    longRunning: false,
    summary: "Remove one subscription-backed CLI provider entry from research.yaml.",
    semantics: "changes provider configuration only; writes no research object and no event",
  },
  "provider.cli.scan": {
    permission: "read",
    humanOnly: false,
    longRunning: false,
    summary: "Detect the supported local CLIs: installed, version, login, bounded mode, models.",
    semantics: "runs local version/login/help probes; edits nothing and sends no research content",
  },
  "provider.cli.test": {
    permission: "read",
    humanOnly: true,
    longRunning: false,
    summary: "Run one minimal schema-validated request through a configured CLI provider.",
    semantics: "sends one test prompt off the workstation under the privacy policy; stages nothing",
  },
  "provider.list": {
    permission: "read",
    humanOnly: false,
    longRunning: false,
    summary: "Every configured model, with what it accepts and whether it is available.",
    semantics: "reads configuration and the project's egress disclosure; for configured local CLIs it reads the cached local detection probes; sends no research content, reveals no credential, and changes no state",
  },
  "question.create": {
    permission: "mutate",
    humanOnly: true,
    longRunning: false,
    summary: "Register a research question.",
    semantics: "creates an open ResearchQuestion; answers nothing",
  },
  "question.list": {
    permission: "read",
    humanOnly: false,
    longRunning: false,
    summary: "Research questions and what currently bears on them.",
    semantics: "reads canonical state; changes nothing",
  },
  "question.resolve": {
    permission: "mutate",
    humanOnly: true,
    longRunning: false,
    summary: "Answer a research question and capture the answer as a note.",
    semantics: "moves a ResearchQuestion to answered; writes no evidence",
  },
  "question.update": {
    permission: "mutate",
    humanOnly: true,
    longRunning: false,
    summary: "Move a question's status and relink what bears on it.",
    semantics: "changes a ResearchQuestion's status and links; writes no evidence",
  },
  "retrieval.resolve_source": {
    permission: "read",
    humanOnly: false,
    longRunning: false,
    summary: "Reopen a reference at its exact source location.",
    semantics: "reads a source anchor; changes nothing",
  },
  "retrieval.search": {
    permission: "read",
    humanOnly: false,
    longRunning: false,
    summary: "Search the corpus and accepted state, accepted state first.",
    semantics: "reads the deletable indexes; changes nothing",
  },
  "review.accept": {
    permission: "mutate",
    humanOnly: true,
    longRunning: false,
    summary: "Accept one staged candidate, named by its staging id.",
    semantics: "creates accepted Evidence from a staged candidate and marks the candidate reviewed; requires a human actor",
  },
  "review.accept_batch": {
    permission: "mutate",
    humanOnly: true,
    longRunning: false,
    summary: "Accept every candidate meeting the Product 24.4 batch conditions.",
    semantics: "creates accepted Evidence for candidates meeting deterministic conditions; requires a human actor and a permitting policy",
  },
  "review.candidate": {
    permission: "read",
    humanOnly: false,
    longRunning: false,
    summary: "One staged candidate, verbatim, as a review action posts it back.",
    semantics: "reads a staged proposal; accepts nothing and changes nothing",
  },
  "review.defer": {
    permission: "stage",
    humanOnly: true,
    longRunning: false,
    summary: "Put one candidate aside; it stays in the queue.",
    semantics: "records the researcher's note on a staged candidate; accepts nothing",
  },
  "review.edit": {
    permission: "mutate",
    humanOnly: true,
    longRunning: false,
    summary: "Accept the researcher's corrected Evidence for one candidate.",
    semantics: "creates accepted Evidence from corrected content; the source anchor may never move, and it requires a human actor",
  },
  "review.inbox": {
    permission: "read",
    humanOnly: false,
    longRunning: false,
    summary: "The review queue, in Product 24.2 priority order.",
    semantics: "reads staged candidates and their conflicts; accepts nothing",
  },
  "review.qualify": {
    permission: "mutate",
    humanOnly: true,
    longRunning: false,
    summary: "Accept one candidate with the condition it holds under.",
    semantics: "creates accepted Evidence carrying a qualification; requires a human actor",
  },
  "review.reject": {
    permission: "mutate",
    humanOnly: true,
    longRunning: false,
    summary: "Refuse one candidate, with the reason recorded beside the corpus.",
    semantics: "records a refusal so the same proposal is recognised again; creates no Evidence and requires a human actor",
  },
  "review.request_more": {
    permission: "stage",
    humanOnly: true,
    longRunning: false,
    summary: "Ask for more evidence; the question is captured as a durable note.",
    semantics: "records the request on the staged candidate and captures it as a low-authority note; accepts nothing",
  },
  "review.resolve_conflict": {
    permission: "mutate",
    humanOnly: true,
    longRunning: false,
    summary: "Resolve a conflicting proposal the researcher's way.",
    semantics: "accepts, rejects, or defers one candidate; the reason is recorded",
  },
  "review.split": {
    permission: "mutate",
    humanOnly: true,
    longRunning: false,
    summary: "Accept the source fact and deal with its interpretation separately.",
    semantics: "creates exactly one accepted Evidence for the source half of a candidate and stages or refuses the interpretation half; requires a human actor",
  },
  "run.cancel": {
    permission: "stage",
    humanOnly: false,
    longRunning: false,
    summary: "Ask a running workflow to stop before its next stage.",
    semantics: "sets a durable cancel flag on regenerable run state",
  },
  "run.status": {
    permission: "read",
    humanOnly: false,
    longRunning: false,
    summary: "The durable record of one long-running workflow run.",
    semantics: "reads regenerable run state; changes nothing",
  },
  "search_run.get": {
    permission: "read",
    humanOnly: false,
    longRunning: false,
    summary: "One discovery run with its candidates and the metadata they propose.",
    semantics: "reads a recorded SearchRun and derives the metadata its candidates offer; proposes nothing to the corpus and changes nothing",
  },
  "search_run.list": {
    permission: "read",
    humanOnly: false,
    longRunning: false,
    summary: "Recorded discovery runs with their funnel counts, newest first.",
    semantics: "reads canonical state; changes nothing",
  },
  "search_run.record": {
    permission: "mutate",
    humanOnly: true,
    longRunning: false,
    summary: "Persist a reproducible discovery operation.",
    semantics: "records what was searched, where, and when; adds nothing to the corpus",
  },
  "session.configure": {
    permission: "mutate",
    humanOnly: true,
    longRunning: false,
    summary: "Bind a session to a runtime and model, or to a research.yaml entry, or clear it; research.yaml is untouched.",
    semantics: "writes private working context; creates no accepted scientific state",
  },
  "session.create": {
    permission: "mutate",
    humanOnly: true,
    longRunning: false,
    summary: "Open a durable conversation session bound to this project.",
    semantics: "writes private working context; creates no accepted scientific state",
  },
  "session.get": {
    permission: "read",
    humanOnly: false,
    longRunning: false,
    summary: "One session's transcript, attachments, and recorded receipts.",
    semantics: "reads durable private working context; changes nothing",
  },
  "session.list": {
    permission: "read",
    humanOnly: false,
    longRunning: false,
    summary: "Every conversation session in this project.",
    semantics: "reads durable private working context; changes nothing",
  },
  "session.promote": {
    permission: "mutate",
    humanOnly: true,
    longRunning: false,
    summary: "Promote an excerpt to a note, question, claim, or decision candidate.",
    semantics: "copies an excerpt into reviewable state with provenance to the session and message; the message is untouched, review is not bypassed, and evidence from prose is refused",
  },
  "session.rename": {
    permission: "mutate",
    humanOnly: true,
    longRunning: false,
    summary: "Retitle a session; its ids and transcript are untouched.",
    semantics: "writes private working context; creates no accepted scientific state",
  },
  "session.retry": {
    permission: "mutate",
    humanOnly: true,
    longRunning: true,
    summary: "Answer again as a new attempt, keeping the failed one.",
    semantics: "adds a new model attempt; the failed attempt's record is kept",
  },
  "session.search": {
    permission: "read",
    humanOnly: false,
    longRunning: false,
    summary: "Sessions whose title or messages contain a query.",
    semantics: "reads durable private working context; changes nothing",
  },
  "session.send": {
    permission: "mutate",
    humanOnly: true,
    longRunning: true,
    summary: "Send a message and stream the answer into a durable run.",
    semantics: "appends to a private transcript and records what the model was shown; creates no accepted scientific state",
  },
  "session.stop": {
    permission: "mutate",
    humanOnly: true,
    longRunning: false,
    summary: "Stop a streaming answer, keeping what already arrived.",
    semantics: "cancels a run and marks the partial answer incomplete",
  },
  "session.summarize": {
    permission: "mutate",
    humanOnly: true,
    longRunning: false,
    summary: "Regenerate a session's derived summary from its transcript.",
    semantics: "rewrites a derived summary of private working context; a summary never outranks the transcript, and neither outranks accepted state",
  },
  "state.index": {
    permission: "read",
    humanOnly: false,
    longRunning: false,
    summary: "Every navigation list - works, claims, questions, decisions - in one read.",
    semantics: "reads canonical state; changes nothing",
  },
  "state.rebuild": {
    permission: "admin",
    humanOnly: true,
    longRunning: false,
    summary: "Rebuild the deletable projection from canonical files.",
    semantics: "rebuilds regenerable state only; canonical files are never written",
  },
  "state.stale": {
    permission: "read",
    humanOnly: false,
    longRunning: false,
    summary: "What is out of date, highest scientific impact first.",
    semantics: "reads recorded stale marks; recomputes and rewrites nothing",
  },
  "synthesis.build_matrix": {
    permission: "mutate",
    humanOnly: true,
    longRunning: false,
    summary: "Persist a cross-paper comparison matrix.",
    semantics: "writes a synthesis matrix over accepted evidence; proposes no new facts",
  },
  "synthesis.compare": {
    permission: "read",
    humanOnly: false,
    longRunning: false,
    summary: "One field across the corpus, as a comparison table.",
    semantics: "reads an existing synthesis matrix; proposes no classification",
  },
  "taxonomy.put": {
    permission: "mutate",
    humanOnly: true,
    longRunning: false,
    summary: "Write a taxonomy authorised by an accepted Decision.",
    semantics: "replaces a classification vocabulary; downstream classifications go stale",
  },
  "work.add_artifact": {
    permission: "mutate",
    humanOnly: true,
    longRunning: false,
    summary: "Attach a new immutable file to an existing Work.",
    semantics: "adds an Artifact (and a Version when needed); never overwrites one",
  },
  "work.get": {
    permission: "read",
    humanOnly: false,
    longRunning: false,
    summary: "Read one Work with its versions, artifacts, and derived counts.",
    semantics: "reads corpus state; changes nothing",
  },
  "work.interrogate": {
    permission: "stage",
    humanOnly: false,
    longRunning: true,
    summary: "Ask a Work the interrogation schema's questions; returns a run id.",
    semantics: "stages evidence candidates under .research/staging; accepts nothing",
  },
  "work.list": {
    permission: "read",
    humanOnly: false,
    longRunning: false,
    summary: "Every Work in the corpus, with its files and evidence counts.",
    semantics: "reads canonical state; changes nothing",
  },
  "work.parse": {
    permission: "mutate",
    humanOnly: true,
    longRunning: false,
    summary: "Parse a Work's artifact into structural blocks and store them.",
    semantics: "stores a derived parse so anchors resolve; changes no evidence",
  },
  "work.register": {
    permission: "mutate",
    humanOnly: true,
    longRunning: false,
    summary: "Register a resolved candidate as a Work, Version, and Artifact.",
    semantics: "creates corpus identity from a resolved candidate; writes no evidence",
  },
  "work.store_blocks": {
    permission: "mutate",
    humanOnly: true,
    longRunning: false,
    summary: "Persist a parse so anchors resolve without re-parsing.",
    semantics: "stores derived document blocks; changes no evidence or claim",
  },
  "work.update_metadata": {
    permission: "mutate",
    humanOnly: true,
    longRunning: false,
    summary: "Fill a Work's empty or undecodable bibliographic fields, with provenance.",
    semantics: "fills missing corpus metadata and records every disagreement; a decodable existing value is never overwritten unless the researcher asks",
  },
};

/** Product 22 names this build does not implement, with the reason it gives a host. */
export const PLANNED_CAPABILITIES: ReadonlyArray<{ name: string; reason: string }> = [
  { name: "project.init", reason: "creating a workspace is an admin action on an arbitrary filesystem path; the daemon is bound to one existing workspace, so it stays a CLI capability" },
  { name: "synthesis.find_pattern", reason: "no pattern-finding service exists yet (Phase 14)" },
];

/**
 * The `review.edit` request schema, as the daemon publishes it. The Evidence
 * editor validates a hand edit against its `edited` property before posting;
 * the daemon validates it again and its refusal is what counts.
 */
export const EDIT_CANDIDATE_SCHEMA = {
  "$defs": {
    "BoundingBox": {
      "additionalProperties": false,
      "description": "Page geometry in parser coordinates, origin at the top-left of the page.",
      "properties": {
        "x0": {
          "title": "X0",
          "type": "number"
        },
        "x1": {
          "title": "X1",
          "type": "number"
        },
        "y0": {
          "title": "Y0",
          "type": "number"
        },
        "y1": {
          "title": "Y1",
          "type": "number"
        }
      },
      "required": [
        "x0",
        "y0",
        "x1",
        "y1"
      ],
      "title": "BoundingBox",
      "type": "object"
    },
    "Evidence": {
      "additionalProperties": false,
      "description": "Source-grounded evidence with epistemic classification (Product 9).",
      "properties": {
        "content": {
          "$ref": "#/$defs/EvidenceContent"
        },
        "created_at": {
          "format": "date-time",
          "title": "Created At",
          "type": "string"
        },
        "decisions": {
          "default": [],
          "items": {
            "pattern": "^D\\d{4,}$",
            "type": "string"
          },
          "title": "Decisions",
          "type": "array"
        },
        "evidence_type": {
          "$ref": "#/$defs/EvidenceType"
        },
        "id": {
          "pattern": "^E\\d{4,}$",
          "title": "Id",
          "type": "string"
        },
        "origin": {
          "$ref": "#/$defs/EvidenceOrigin"
        },
        "provenance": {
          "$ref": "#/$defs/Provenance"
        },
        "qualification": {
          "anyOf": [
            {
              "type": "string"
            },
            {
              "type": "null"
            }
          ],
          "default": null,
          "title": "Qualification"
        },
        "review_tier": {
          "$ref": "#/$defs/ReviewTier",
          "default": 1
        },
        "schema_version": {
          "default": 1,
          "minimum": 1,
          "title": "Schema Version",
          "type": "integer"
        },
        "source": {
          "$ref": "#/$defs/SourceAnchor"
        },
        "stale": {
          "$ref": "#/$defs/StaleState",
          "default": "fresh"
        },
        "strength": {
          "$ref": "#/$defs/EvidenceStrength"
        },
        "updated_at": {
          "format": "date-time",
          "title": "Updated At",
          "type": "string"
        },
        "verification": {
          "$ref": "#/$defs/VerificationRecord",
          "default": {
            "accepted_by": null,
            "extractor": null,
            "rationale": null,
            "review_action": null,
            "reviewed_at": null,
            "status": "proposed",
            "verdict": null,
            "verifier": null
          }
        }
      },
      "required": [
        "id",
        "provenance",
        "source",
        "content",
        "origin",
        "evidence_type",
        "strength"
      ],
      "title": "Evidence",
      "type": "object"
    },
    "EvidenceContent": {
      "additionalProperties": false,
      "description": "What the evidence says: exact text, optional number, optional absence state.",
      "properties": {
        "exact_text": {
          "default": "",
          "title": "Exact Text",
          "type": "string"
        },
        "field": {
          "anyOf": [
            {
              "type": "string"
            },
            {
              "type": "null"
            }
          ],
          "default": null,
          "title": "Field"
        },
        "labels": {
          "default": [],
          "items": {
            "type": "string"
          },
          "title": "Labels",
          "type": "array"
        },
        "negative_state": {
          "anyOf": [
            {
              "$ref": "#/$defs/NegativeEvidenceState"
            },
            {
              "type": "null"
            }
          ],
          "default": null
        },
        "numeric": {
          "anyOf": [
            {
              "$ref": "#/$defs/NumericValue"
            },
            {
              "type": "null"
            }
          ],
          "default": null
        }
      },
      "title": "EvidenceContent",
      "type": "object"
    },
    "EvidenceOrigin": {
      "description": "Epistemic origin of an evidence object (Product 9.1).",
      "enum": [
        "source_observed",
        "author_claimed",
        "author_interpreted",
        "researcher_inferred",
        "model_proposed",
        "external_metadata"
      ],
      "title": "EvidenceOrigin",
      "type": "string"
    },
    "EvidenceStatus": {
      "description": "Evidence/Interpretation lifecycle status (Product 8.3, 24).",
      "enum": [
        "proposed",
        "verified",
        "accepted",
        "rejected",
        "deferred",
        "stale",
        "superseded"
      ],
      "title": "EvidenceStatus",
      "type": "string"
    },
    "EvidenceStrength": {
      "description": "How directly the source supports the evidence (Product 9.3).",
      "enum": [
        "direct",
        "indirect",
        "derived"
      ],
      "title": "EvidenceStrength",
      "type": "string"
    },
    "EvidenceType": {
      "description": "What kind of statement the evidence carries (Product 9.2).",
      "enum": [
        "method_description",
        "representation_description",
        "experimental_setup",
        "experimental_result",
        "ablation_result",
        "dataset_description",
        "baseline_description",
        "limitation",
        "author_conclusion",
        "definition",
        "theoretical_result",
        "implementation_detail",
        "deployment_assumption",
        "bibliographic_metadata"
      ],
      "title": "EvidenceType",
      "type": "string"
    },
    "NegativeEvidenceState": {
      "description": "Absence states, deliberately distinct (Product 11, principle P5).\n\nA missing lexical hit is `not_found`; `absent` is an audited conclusion.",
      "enum": [
        "absent",
        "not_found",
        "not_reported",
        "not_applicable",
        "unclear"
      ],
      "title": "NegativeEvidenceState",
      "type": "string"
    },
    "NumericValue": {
      "additionalProperties": false,
      "description": "A measured value with the provenance a number needs (Product 12).\n\nThe writer must never silently change metric, unit, dataset, condition, rounding, or\ndenominator, so all of those travel with the value.",
      "properties": {
        "condition": {
          "additionalProperties": {
            "type": "string"
          },
          "title": "Condition",
          "type": "object"
        },
        "dataset": {
          "anyOf": [
            {
              "type": "string"
            },
            {
              "type": "null"
            }
          ],
          "default": null,
          "title": "Dataset"
        },
        "metric": {
          "minLength": 1,
          "title": "Metric",
          "type": "string"
        },
        "parsed": {
          "title": "Parsed",
          "type": "number"
        },
        "raw": {
          "minLength": 1,
          "title": "Raw",
          "type": "string"
        },
        "source_column": {
          "anyOf": [
            {
              "type": "string"
            },
            {
              "type": "null"
            }
          ],
          "default": null,
          "title": "Source Column"
        },
        "source_row": {
          "anyOf": [
            {
              "type": "string"
            },
            {
              "type": "null"
            }
          ],
          "default": null,
          "title": "Source Row"
        },
        "source_table": {
          "minLength": 1,
          "title": "Source Table",
          "type": "string"
        },
        "unit": {
          "anyOf": [
            {
              "type": "string"
            },
            {
              "type": "null"
            }
          ],
          "default": null,
          "title": "Unit"
        }
      },
      "required": [
        "raw",
        "parsed",
        "metric",
        "source_table"
      ],
      "title": "NumericValue",
      "type": "object"
    },
    "Provenance": {
      "additionalProperties": false,
      "description": "Who/what produced a record, and under which workflow run.\n\n``actor`` is an opaque string (``\"human\"``, ``\"human:alice\"``, ``\"vendor-a/model-x\"``,\n``\"local/model-y\"``). The domain never interprets it as a provider vocabulary and\ndefines no provider names of its own.",
      "properties": {
        "actor": {
          "minLength": 1,
          "title": "Actor",
          "type": "string"
        },
        "note": {
          "anyOf": [
            {
              "type": "string"
            },
            {
              "type": "null"
            }
          ],
          "default": null,
          "title": "Note"
        },
        "run_id": {
          "anyOf": [
            {
              "type": "string"
            },
            {
              "type": "null"
            }
          ],
          "default": null,
          "title": "Run Id"
        },
        "source": {
          "$ref": "#/$defs/ProvenanceSource"
        },
        "template_version": {
          "anyOf": [
            {
              "type": "string"
            },
            {
              "type": "null"
            }
          ],
          "default": null,
          "title": "Template Version"
        },
        "workflow": {
          "anyOf": [
            {
              "type": "string"
            },
            {
              "type": "null"
            }
          ],
          "default": null,
          "title": "Workflow"
        }
      },
      "required": [
        "source",
        "actor"
      ],
      "title": "Provenance",
      "type": "object"
    },
    "ProvenanceSource": {
      "description": "Who produced a record. Never a provider or host name; see `Provenance.actor`.",
      "enum": [
        "human",
        "model",
        "system",
        "external_metadata"
      ],
      "title": "ProvenanceSource",
      "type": "string"
    },
    "ReviewAction": {
      "description": "Human review actions (Product 24.3).",
      "enum": [
        "accept",
        "accept_with_qualification",
        "edit",
        "reject",
        "defer",
        "request_more_evidence"
      ],
      "title": "ReviewAction",
      "type": "string"
    },
    "ReviewTier": {
      "description": "Review tier (Product 24.1). Ordered: 0 mechanical, 1 triage, 2 deep review.",
      "enum": [
        0,
        1,
        2
      ],
      "title": "ReviewTier",
      "type": "integer"
    },
    "SourceAnchor": {
      "additionalProperties": false,
      "description": "Exact source location of an evidence object (Product 9).\n\nWork, version, artifact, file hash, block, and text hash are mandatory: an evidence\nobject that cannot be reopened at its source is not evidence.",
      "properties": {
        "artifact": {
          "pattern": "^A\\d{4,}(?:-\\d+)?$",
          "title": "Artifact",
          "type": "string"
        },
        "bbox": {
          "anyOf": [
            {
              "$ref": "#/$defs/BoundingBox"
            },
            {
              "type": "null"
            }
          ],
          "default": null
        },
        "block": {
          "pattern": "^B\\d{4,}$",
          "title": "Block",
          "type": "string"
        },
        "char_end": {
          "anyOf": [
            {
              "minimum": 0,
              "type": "integer"
            },
            {
              "type": "null"
            }
          ],
          "default": null,
          "title": "Char End"
        },
        "char_start": {
          "anyOf": [
            {
              "minimum": 0,
              "type": "integer"
            },
            {
              "type": "null"
            }
          ],
          "default": null,
          "title": "Char Start"
        },
        "file_hash": {
          "pattern": "^sha256:[0-9a-f]{64}$",
          "title": "File Hash",
          "type": "string"
        },
        "page": {
          "anyOf": [
            {
              "minimum": 1,
              "type": "integer"
            },
            {
              "type": "null"
            }
          ],
          "default": null,
          "title": "Page"
        },
        "section_path": {
          "default": [],
          "items": {
            "type": "string"
          },
          "title": "Section Path",
          "type": "array"
        },
        "text_hash": {
          "pattern": "^sha256:[0-9a-f]{64}$",
          "title": "Text Hash",
          "type": "string"
        },
        "version": {
          "pattern": "^V\\d{4,}(?:-\\d+)?$",
          "title": "Version",
          "type": "string"
        },
        "work": {
          "pattern": "^W\\d{4,}$",
          "title": "Work",
          "type": "string"
        }
      },
      "required": [
        "work",
        "version",
        "artifact",
        "file_hash",
        "block",
        "text_hash"
      ],
      "title": "SourceAnchor",
      "type": "object"
    },
    "StaleState": {
      "description": "Dependency freshness (Product 37). Stale objects are never silently rewritten.",
      "enum": [
        "fresh",
        "stale"
      ],
      "title": "StaleState",
      "type": "string"
    },
    "VerificationRecord": {
      "additionalProperties": false,
      "description": "Lifecycle status plus who proposed, verified, and accepted the object.\n\nModel confidence is deliberately absent: it is never an input to acceptance.",
      "properties": {
        "accepted_by": {
          "anyOf": [
            {
              "type": "string"
            },
            {
              "type": "null"
            }
          ],
          "default": null,
          "title": "Accepted By"
        },
        "extractor": {
          "anyOf": [
            {
              "type": "string"
            },
            {
              "type": "null"
            }
          ],
          "default": null,
          "title": "Extractor"
        },
        "rationale": {
          "anyOf": [
            {
              "type": "string"
            },
            {
              "type": "null"
            }
          ],
          "default": null,
          "title": "Rationale"
        },
        "review_action": {
          "anyOf": [
            {
              "$ref": "#/$defs/ReviewAction"
            },
            {
              "type": "null"
            }
          ],
          "default": null
        },
        "reviewed_at": {
          "anyOf": [
            {
              "format": "date-time",
              "type": "string"
            },
            {
              "type": "null"
            }
          ],
          "default": null,
          "title": "Reviewed At"
        },
        "status": {
          "$ref": "#/$defs/EvidenceStatus",
          "default": "proposed"
        },
        "verdict": {
          "anyOf": [
            {
              "$ref": "#/$defs/VerificationVerdict"
            },
            {
              "type": "null"
            }
          ],
          "default": null
        },
        "verifier": {
          "anyOf": [
            {
              "type": "string"
            },
            {
              "type": "null"
            }
          ],
          "default": null,
          "title": "Verifier"
        }
      },
      "title": "VerificationRecord",
      "type": "object"
    },
    "VerificationVerdict": {
      "description": "Outcome reported by a verifier role (Product 20.4).",
      "enum": [
        "supported",
        "partially_supported",
        "contradicted",
        "insufficient_evidence"
      ],
      "title": "VerificationVerdict",
      "type": "string"
    }
  },
  "additionalProperties": false,
  "description": "`review.edit`: accept the researcher's corrected Evidence for one candidate.\n\nAn edit may correct what the evidence says; it may never move the source anchor, which\n`evidence.accept` refuses (ADR-002). The corrected object's own id is ignored: the real\n`EvidenceId` is allocated at acceptance, as it is for every other review action.",
  "properties": {
    "candidate_id": {
      "title": "Candidate Id",
      "type": "string"
    },
    "edited": {
      "$ref": "#/$defs/Evidence"
    }
  },
  "required": [
    "candidate_id",
    "edited"
  ],
  "title": "EditCandidateRequest",
  "type": "object"
} as const;

/** The property of that request the hand-edited object goes in. */
export const EDIT_CANDIDATE_PROPERTY = "edited";
