/**
 * Generated by scripts/gen-types.mjs from the daemon snapshots. Do not edit by hand.
 *
 * Refresh with:
 *   uv run python web/scripts/export_backend_json.py   # re-export the snapshots
 *   pnpm gen:types                                     # regenerate this file
 */

export interface paths {
    "/artifacts/{artifact_id}/bytes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Artifact Bytes
         * @description The immutable bytes an evidence anchor was accepted against (Product 42 D).
         *
         *     Read-only and byte-identical: there is no counterpart that writes an artifact,
         *     because an artifact is registered once and never edited (ADR-002).
         */
        get: operations["artifact_bytes_artifacts__artifact_id__bytes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/blocks/{artifact_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Blocks
         * @description The stored parse of one artifact: page, order, and geometry for each block.
         *
         *     This is what lets a source pane draw the evidence span on the page without
         *     re-parsing the PDF, which is why the blocks are canonical (Product 8.1).
         */
        get: operations["blocks_blocks__artifact_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/candidates/{candidate_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Candidate
         * @description One staged candidate, verbatim, so a review action can post the object back.
         *
         *     Staging is a proposal store with no authority (ADR-003): reading it changes nothing,
         *     and accepting what it holds still goes through `evidence.accept`.
         */
        get: operations["candidate_candidates__candidate_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/capabilities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Capabilities
         * @description Every named capability with its permission and both JSON schemas.
         */
        get: operations["capabilities_capabilities_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/capabilities/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Invoke
         * @description Invoke one capability. The body is that capability's request object.
         */
        post: operations["invoke_capabilities__name__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Whether this daemon can serve its workspace, and what it is serving.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/index": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Index
         * @description Everything the cockpit's navigation lists, summarised, in one read.
         */
        get: operations["index_index_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/manuscript/builds/{build_id}/pdf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Manuscript Build Pdf
         * @description The PDF of one build, inline. `latest` and `last-good` are accepted as ids.
         *
         *     A failed build has no PDF of its own; the response is then the last good one, which
         *     is what the preview keeps showing while the diagnostics describe the source as it
         *     is now. A workspace that has never compiled answers 404 rather than an empty file.
         */
        get: operations["manuscript_build_pdf_manuscript_builds__build_id__pdf_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/objects/{object_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Obj
         * @description One canonical object, read through the repository's typed accessors.
         */
        get: operations["obj_objects__object_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Overview
         * @description What needs attention now, composed server-side (Product 26, principle P10).
         */
        get: operations["overview_overview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Run
         * @description The durable record of one long-running workflow.
         */
        get: operations["run_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cancel
         * @description Ask a run to stop before its next stage; the flag is durable.
         */
        post: operations["cancel_runs__run_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Run Events
         * @description Stream one run's deltas and its terminal status (v1.1 plan SS0.4).
         *
         *     A read: `read` permission, like every other run route, and the same principal
         *     resolution. Watching an answer arrive is not authority to have asked for it.
         */
        get: operations["run_events_runs__run_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{session_id}/attachments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Add Attachment Bytes
         * @description Attach a file to a session. The one non-capability write, and session-only.
         *
         *     The body is the raw file, `Content-Type` is its media type, and `?filename=` is
         *     display metadata: only its basename is kept and it never selects a path. The bytes
         *     become a `selected -> validating -> ready` attachment (or a `failed` one carrying
         *     the reason), and no corpus object is created — `attachment.save_to_corpus` is the
         *     only thing that does that.
         */
        post: operations["add_attachment_bytes_sessions__session_id__attachments_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{session_id}/attachments/{attachment_id}/bytes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Attachment Bytes
         * @description The attachment's original bytes, inline, exactly as they were stored.
         *
         *     Read-only and byte-identical: an attachment's bytes are immutable once stored, so
         *     there is no route that rewrites them.
         */
        get: operations["attachment_bytes_sessions__session_id__attachments__attachment_id__bytes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{session_id}/attachments/{attachment_id}/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Attachment Preview
         * @description A PNG projection of one page: a thumbnail for an image, a render for a PDF.
         *
         *     The file lives under `.research/cache/attachments/` and is rendered on demand, so
         *     deleting the cache costs a re-render and never an attachment (Product 8.2).
         */
        get: operations["attachment_preview_sessions__session_id__attachments__attachment_id__preview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AnchorSummary
         * @description One manuscript sentence bound to a Claim (Product 30.1).
         */
        AnchorSummary: {
            /**
             * Citation Keys
             * @default []
             */
            citation_keys: string[];
            /** Claim */
            claim: string;
            /** File */
            file: string;
            /** Line Start */
            line_start: number;
            /** Sentence */
            sentence: string;
            /** Stale */
            stale: string;
            /** Status */
            status: string;
        };
        /**
         * ArtifactBlocks
         * @description Every stored block of one artifact, in reading order, with its file identity.
         */
        ArtifactBlocks: {
            /** Artifact */
            artifact: string;
            /**
             * Blocks
             * @default []
             */
            blocks: components["schemas"]["BlockView"][];
            /** File Hash */
            file_hash: string;
            /** Mime Type */
            mime_type: string;
            /** Page Count */
            page_count: number;
            /** Version */
            version: string;
            /** Work */
            work: string;
        };
        /**
         * ArtifactSummary
         * @description One immutable file of a Work, and whether a parse of it is stored.
         */
        ArtifactSummary: {
            /** Id */
            id: string;
            /** Kind */
            kind: string;
            /** Mime Type */
            mime_type: string;
            /** Original Filename */
            original_filename: string;
            /** Parsed */
            parsed: boolean;
            /** Size Bytes */
            size_bytes: number;
            /** Version */
            version: string;
        };
        /**
         * AttachmentView
         * @description One session attachment as every transport sees it.
         */
        AttachmentView: {
            /** Artifact */
            artifact?: string | null;
            /** Content Hash */
            content_hash?: string | null;
            /** Created At */
            created_at?: string | null;
            /** Description */
            description?: string | null;
            /** Failure Reason */
            failure_reason?: string | null;
            /** Filename */
            filename: string;
            /** Id */
            id: string;
            /** Media Type */
            media_type: string;
            /** Page Count */
            page_count?: number | null;
            /** Session */
            session: string;
            /** Size Bytes */
            size_bytes: number;
            /** State */
            state: string;
            /** Updated At */
            updated_at?: string | null;
            /** Version */
            version?: string | null;
            /**
             * Visibility
             * @default private
             */
            visibility: string;
            /** Work */
            work?: string | null;
        };
        /**
         * AttentionGroup
         * @description One attention surface of Product 26: its size, where it lives, and its top items.
         */
        AttentionGroup: {
            /** Count */
            count: number;
            /**
             * Items
             * @default []
             */
            items: components["schemas"]["AttentionItem"][];
            /** Kind */
            kind: string;
            /** Label */
            label: string;
            /** Route */
            route: string;
            /**
             * Surface
             * @default decide
             */
            surface: string;
        };
        /**
         * AttentionItem
         * @description One thing waiting for the researcher, already ordered by the server.
         */
        AttentionItem: {
            /**
             * Detail
             * @default
             */
            detail: string;
            /** Id */
            id: string;
            /** Label */
            label: string;
            /**
             * Priority
             * @default 0
             */
            priority: number;
            /**
             * Route
             * @default
             */
            route: string;
        };
        /**
         * BlockView
         * @description One parsed block with the page geometry a source pane draws a highlight on.
         */
        BlockView: {
            /** Bbox */
            bbox?: [
                number,
                number,
                number,
                number
            ] | null;
            /** Id */
            id: string;
            /** Kind */
            kind: string;
            /** Order */
            order: number;
            /** Page */
            page: number;
            /**
             * Section Path
             * @default []
             */
            section_path: string[];
            /** Text */
            text: string;
        };
        /**
         * CandidateView
         * @description One staged candidate, verbatim, as `evidence.accept` takes it.
         *
         *     The Review Inbox summarises a candidate; a review action has to send the object itself,
         *     so a client reads it here and posts `evidence` back unchanged. Staging carries no
         *     authority (ADR-003), which is why this is the only shape in this module that is not a
         *     canonical object.
         */
        CandidateView: {
            /** Anchor Status */
            anchor_status: string;
            /** Artifact */
            artifact: string;
            /** Candidate Id */
            candidate_id: string;
            /** Evidence */
            evidence?: {
                [key: string]: unknown;
            };
            /** Extraction */
            extraction?: {
                [key: string]: unknown;
            };
            /** Field */
            field: string;
            /** Review Action */
            review_action?: string | null;
            /** Status */
            status: string;
            /** Verdict */
            verdict?: string | null;
            /** Verification */
            verification?: {
                [key: string]: unknown;
            } | null;
            /** Verifier */
            verifier?: string | null;
            /** Work */
            work: string;
        };
        /**
         * CapabilityCatalog
         * @description What a host can call, and what it cannot call yet.
         */
        CapabilityCatalog: {
            /**
             * Capabilities
             * @default []
             */
            capabilities: components["schemas"]["CapabilityDescriptor"][];
            /**
             * Planned
             * @default []
             */
            planned: components["schemas"]["PlannedCapability"][];
        };
        /**
         * CapabilityDescriptor
         * @description One capability as a host sees it: name, authority, and both JSON schemas.
         */
        CapabilityDescriptor: {
            /** Human Only */
            human_only: boolean;
            /** Long Running */
            long_running: boolean;
            /** Name */
            name: string;
            permission: components["schemas"]["Permission"];
            /** Request Schema */
            request_schema: {
                [key: string]: unknown;
            };
            /** Response Schema */
            response_schema: {
                [key: string]: unknown;
            };
            /** Scientific Semantics */
            scientific_semantics: string;
            /** Summary */
            summary: string;
        };
        /**
         * CapabilityResponse
         * @description One capability result: the typed payload, or the error that replaced it.
         */
        CapabilityResponse: {
            /** Capability */
            capability: string;
            error?: components["schemas"]["ErrorBody"] | null;
            /** Ok */
            ok: boolean;
            /** Result */
            result?: {
                [key: string]: unknown;
            } | null;
            /** Run Id */
            run_id?: string | null;
        };
        /**
         * ChangeEntry
         * @description One thing that changed while the researcher was away, as the daemon recorded it.
         */
        ChangeEntry: {
            /** At */
            at: string;
            /**
             * Detail
             * @default
             */
            detail: string;
            /** Id */
            id: string;
            /** Kind */
            kind: string;
            /** Label */
            label: string;
            /**
             * Route
             * @default
             */
            route: string;
            /** When */
            when: string;
        };
        /**
         * ClaimSummary
         * @description One Claim as the Claim explorer lists it: what it asks, and what it may say.
         */
        ClaimSummary: {
            /** Allowed Strength */
            allowed_strength: string;
            /**
             * Contradicting
             * @default 0
             */
            contradicting: number;
            /** Id */
            id: string;
            /** Maximum Defensible Wording */
            maximum_defensible_wording?: string | null;
            /**
             * Qualifying
             * @default 0
             */
            qualifying: number;
            /** Requested Strength */
            requested_strength: string;
            /** Stale */
            stale: string;
            /** Statement */
            statement: string;
            /** Status */
            status: string;
            /**
             * Supporting
             * @default 0
             */
            supporting: number;
            /** Type */
            type: string;
        };
        /**
         * ConflictPosition
         * @description One side of a disagreement: who said it, and what they decided.
         */
        ConflictPosition: {
            /** Decision */
            decision?: {
                [key: string]: unknown;
            };
            /** Label */
            label: string;
            /** Model */
            model: string;
            /** Provider */
            provider: string;
            /** Rationale */
            rationale?: string | null;
        };
        /**
         * ConflictView
         * @description One open disagreement as the cockpit shows it (Product 25): every side, no winner.
         */
        ConflictView: {
            /** Conflict Id */
            conflict_id: string;
            /** Created At */
            created_at: string;
            /**
             * Differing Fields
             * @default []
             */
            differing_fields: string[];
            /** Kind */
            kind: string;
            /**
             * Positions
             * @default []
             */
            positions: components["schemas"]["ConflictPosition"][];
            /**
             * Proposed Changes
             * @default []
             */
            proposed_changes: {
                [key: string]: unknown;
            }[];
            /** Status */
            status: string;
            /** Subject */
            subject: string;
            /** Summary */
            summary: string;
            /** Tier */
            tier: number;
        };
        /**
         * CountEntry
         * @description One labelled tally. Never a model-confidence number (Product 26, 43).
         */
        CountEntry: {
            /** Count */
            count: number;
            /** Key */
            key: string;
        };
        /**
         * DecisionSummary
         * @description One researcher Decision: the visible record an override or revision leaves.
         */
        DecisionSummary: {
            /** Auditor Recommendation */
            auditor_recommendation?: string | null;
            /** Claim */
            claim?: string | null;
            /** Id */
            id: string;
            /** Rationale */
            rationale: string;
            /** Researcher Selected */
            researcher_selected?: string | null;
            /** Status */
            status: string;
            /** Title */
            title?: string | null;
            /** Type */
            type: string;
        };
        /**
         * ErrorBody
         * @description Why a call failed, identically on every transport.
         */
        ErrorBody: {
            /** Capability */
            capability?: string | null;
            /** Code */
            code: string;
            /** Message */
            message: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthReport
         * @description Whether the daemon can serve this workspace at all.
         */
        HealthReport: {
            /** Capabilities */
            capabilities: number;
            /** Ok */
            ok: boolean;
            /** Project */
            project: string;
            /** Review Policy */
            review_policy: string;
            /** Version */
            version: string;
            /** Workspace */
            workspace: string;
        };
        /**
         * MatrixSummary
         * @description One synthesis matrix: its rows, its fields, and whether it has gone stale.
         */
        MatrixSummary: {
            /**
             * Cells
             * @default 0
             */
            cells: number;
            /**
             * Fields
             * @default []
             */
            fields: string[];
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Stale */
            stale: string;
            /** Taxonomy */
            taxonomy?: string | null;
            /**
             * Works
             * @default 0
             */
            works: number;
        };
        /**
         * ObjectView
         * @description One canonical object, read through the repository's typed accessors.
         */
        ObjectView: {
            /** Id */
            id: string;
            /** Kind */
            kind: string;
            /** Object */
            object: {
                [key: string]: unknown;
            };
        };
        /**
         * OverviewCounts
         * @description The size of the project, as the Overview header states it.
         */
        OverviewCounts: {
            /**
             * Accepted Evidence
             * @default 0
             */
            accepted_evidence: number;
            /**
             * Artifacts
             * @default 0
             */
            artifacts: number;
            /**
             * Claims
             * @default 0
             */
            claims: number;
            /**
             * Decisions
             * @default 0
             */
            decisions: number;
            /**
             * Manuscript Anchors
             * @default 0
             */
            manuscript_anchors: number;
            /**
             * Matrices
             * @default 0
             */
            matrices: number;
            /**
             * Questions
             * @default 0
             */
            questions: number;
            /**
             * Works
             * @default 0
             */
            works: number;
        };
        /**
         * OverviewReport
         * @description `GET /overview`: next actions first, then claim health and open questions.
         *
         *     The ordering, the grouping, and every rule that decides whether something needs
         *     attention are settled here so no client re-derives them (Product 5 P10, 26).
         */
        OverviewReport: {
            /**
             * Actor
             * @default human
             */
            actor: string;
            /**
             * Attention
             * @default []
             */
            attention: components["schemas"]["AttentionGroup"][];
            /**
             * Attention Summary
             * @default
             */
            attention_summary: string;
            /**
             * Claim Health
             * @default []
             */
            claim_health: components["schemas"]["CountEntry"][];
            /**
             * Conflicts
             * @default []
             */
            conflicts: components["schemas"]["ConflictView"][];
            counts?: components["schemas"]["OverviewCounts"];
            /**
             * Next Decision Id
             * @default
             */
            next_decision_id: string;
            /**
             * Open Questions
             * @default []
             */
            open_questions: components["schemas"]["AttentionItem"][];
            /**
             * Principal
             * @default human
             */
            principal: string;
            /** Project */
            project: string;
            /** Review Policy */
            review_policy: string;
            since_last_session?: components["schemas"]["RecentChanges"];
            /** Workspace */
            workspace: string;
        };
        /**
         * Permission
         * @description What a capability is allowed to touch.
         * @enum {string}
         */
        Permission: "read" | "stage" | "mutate" | "admin";
        /**
         * PlannedCapability
         * @description A Product 22 name with no implementation in this build, and why.
         */
        PlannedCapability: {
            /** Name */
            name: string;
            /** Reason */
            reason: string;
        };
        /**
         * QuestionSummary
         * @description One ResearchQuestion and what currently bears on it.
         */
        QuestionSummary: {
            /**
             * Claims
             * @default []
             */
            claims: string[];
            /** Id */
            id: string;
            /** Question */
            question: string;
            /** Remaining Uncertainty */
            remaining_uncertainty?: string | null;
            /** Stale */
            stale: string;
            /** Status */
            status: string;
        };
        /**
         * RecentChanges
         * @description `OverviewReport.since_last_session`: what changed while the researcher was away.
         *
         *     **Where the window opens.** The daemon reads this project's conversation sessions,
         *     keeps the ones that recorded a message, and orders them by that message, newest first.
         *     With two or more, the window opens at the end of the session *before* the most recent
         *     one, so what a researcher sees on returning is the work of their last sitting and
         *     everything after it — which is the question "what changed since I last worked" actually
         *     asks. With fewer than two sessions there is nothing to bound a window with, so the
         *     window is the last seven days. `basis` names which rule applied (`previous_session`,
         *     `recent_window`, or `no_history` for a project that has recorded no research yet) and
         *     `summary` says it in words, so nothing on screen has to guess.
         *
         *     **What counts as a change.** Works added, evidence accepted, claims promoted or
         *     reclassified, and decisions taken, read from the Git-visible semantic event log
         *     (Product 19.3); conflicts opened or resolved, read from the conflict store. Newest
         *     first, capped, with `more` saying in words what the cap left out. Every judgement here
         *     is the daemon's: a client displays this list and never rebuilds it (Product 5 P10).
         */
        RecentChanges: {
            /**
             * Basis
             * @default no_history
             */
            basis: string;
            /**
             * Entries
             * @default []
             */
            entries: components["schemas"]["ChangeEntry"][];
            /**
             * More
             * @default
             */
            more: string;
            /**
             * Since
             * @default
             */
            since: string;
            /**
             * Summary
             * @default
             */
            summary: string;
            /**
             * Total
             * @default 0
             */
            total: number;
        };
        /**
         * RunStatus
         * @description A durable workflow run: the answer to "is it done yet?" without an open connection.
         */
        RunStatus: {
            /**
             * Cancel Requested
             * @default false
             */
            cancel_requested: boolean;
            /** Created At */
            created_at: string;
            /** Error */
            error?: string | null;
            /** Run Id */
            run_id: string;
            /**
             * Stages
             * @default []
             */
            stages: components["schemas"]["StageView"][];
            /** Status */
            status: string;
            /** Updated At */
            updated_at: string;
            /** Workflow */
            workflow: string;
            /** Workflow Version */
            workflow_version: string;
        };
        /**
         * StageView
         * @description One stage of a durable workflow run.
         */
        StageView: {
            /**
             * Attempts
             * @default 0
             */
            attempts: number;
            /** Name */
            name: string;
            /** Status */
            status: string;
        };
        /**
         * TaxonomySummary
         * @description One project taxonomy and the Decisions that approved its terms.
         */
        TaxonomySummary: {
            /**
             * Decisions
             * @default []
             */
            decisions: string[];
            /** Name */
            name: string;
            /**
             * Terms
             * @default []
             */
            terms: {
                [key: string]: unknown;
            }[];
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * WorkSummary
         * @description One Work as the Corpus list shows it.
         */
        WorkSummary: {
            /**
             * Artifacts
             * @default []
             */
            artifacts: components["schemas"]["ArtifactSummary"][];
            /**
             * Authors
             * @default []
             */
            authors: string[];
            /**
             * Evidence
             * @default 0
             */
            evidence: number;
            /** Id */
            id: string;
            /** Screening */
            screening: string;
            /** Title */
            title: string;
            /** Venue */
            venue?: string | null;
            /**
             * Versions
             * @default 0
             */
            versions: number;
            /** Year */
            year?: number | null;
        };
        /**
         * WorkspaceIndex
         * @description Everything a navigation lists, summarised, in one read (`GET /index`).
         *
         *     Summaries, not objects: a list view needs identity and status, and the full object is
         *     one `GET /objects/<id>` away. Nothing here is derived beyond counting what the canonical
         *     files already record.
         */
        WorkspaceIndex: {
            /**
             * Anchors
             * @default []
             */
            anchors: components["schemas"]["AnchorSummary"][];
            /**
             * Claims
             * @default []
             */
            claims: components["schemas"]["ClaimSummary"][];
            /**
             * Decisions
             * @default []
             */
            decisions: components["schemas"]["DecisionSummary"][];
            /**
             * Matrices
             * @default []
             */
            matrices: components["schemas"]["MatrixSummary"][];
            /**
             * Questions
             * @default []
             */
            questions: components["schemas"]["QuestionSummary"][];
            /**
             * Taxonomies
             * @default []
             */
            taxonomies: components["schemas"]["TaxonomySummary"][];
            /**
             * Works
             * @default []
             */
            works: components["schemas"]["WorkSummary"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    artifact_bytes_artifacts__artifact_id__bytes_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                artifact_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    blocks_blocks__artifact_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                artifact_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArtifactBlocks"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    candidate_candidates__candidate_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                candidate_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CandidateView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    capabilities_capabilities_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CapabilityCatalog"];
                };
            };
        };
    };
    invoke_capabilities__name__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                } | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CapabilityResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthReport"];
                };
            };
        };
    };
    index_index_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceIndex"];
                };
            };
        };
    };
    manuscript_build_pdf_manuscript_builds__build_id__pdf_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                build_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    obj_objects__object_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                object_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ObjectView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    overview_overview_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OverviewReport"];
                };
            };
        };
    };
    run_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_runs__run_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_events_runs__run_id__events_get: {
        parameters: {
            query?: {
                /** @description Replay deltas from this index; 0 replays the whole answer. */
                after?: number;
            };
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_attachment_bytes_sessions__session_id__attachments_post: {
        parameters: {
            query?: {
                /** @description Display name for the attachment. Metadata only; never a path. */
                filename?: string | null;
                /** @description Researcher-supplied description or alt text, kept apart from reading. */
                description?: string | null;
            };
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttachmentView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    attachment_bytes_sessions__session_id__attachments__attachment_id__bytes_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
                attachment_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    attachment_preview_sessions__session_id__attachments__attachment_id__preview_get: {
        parameters: {
            query?: {
                /** @description 1-based page of the preview to render. */
                page?: number;
            };
            header?: never;
            path: {
                session_id: string;
                attachment_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
