// Regenerate the cockpit's API types from the checked-in daemon snapshots.
//
//   node scripts/gen-types.mjs      (or: pnpm gen:types)
//
// It starts nothing and calls nothing: `openapi.json` and `capabilities.json` are snapshots
// exported from the FastAPI app by `uv run python web/scripts/export_backend_json.py`.
// Refresh those first when a route or a capability changes, then run this.
//
// Two files come out:
//   src/api/types.gen.ts        - route and DTO types, from openapi-typescript.
//   src/api/capabilities.gen.ts - the capability names, their permissions, and the one JSON
//                                 schema the Evidence editor validates against.

import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import openapiTS, { astToString } from 'openapi-typescript';

const here = dirname(fileURLToPath(import.meta.url));
const web = resolve(here, '..');
const out = resolve(web, 'src/api');

/**
 * The capability whose request schema the Evidence editor validates a hand edit against.
 *
 * `review.edit` is the call the Edit action makes: the staging id, plus the corrected
 * `Evidence` under `edited`. Validating against the request the cockpit actually posts is
 * what keeps the local check honest.
 */
const EDITED_CAPABILITY = 'review.edit';
/** The property of that request holding the object the researcher typed. */
const EDITED_PROPERTY = 'edited';

const BANNER = `/**
 * Generated by scripts/gen-types.mjs from the daemon snapshots. Do not edit by hand.
 *
 * Refresh with:
 *   uv run python web/scripts/export_backend_json.py   # re-export the snapshots
 *   pnpm gen:types                                     # regenerate this file
 */`;

async function readJson(name) {
  return JSON.parse(await readFile(resolve(web, name), 'utf8'));
}

/** Route and DTO types straight from the daemon's OpenAPI document. */
async function generateRouteTypes() {
  const ast = await openapiTS(pathToFileURL(resolve(web, 'openapi.json')));
  await writeFile(resolve(out, 'types.gen.ts'), `${BANNER}\n\n${astToString(ast)}`, 'utf8');
  return 'src/api/types.gen.ts';
}

/**
 * The capability catalog as TypeScript: the name union a client is checked against, what
 * each name is allowed to touch, and the request schema for the one hand-edited object.
 */
async function generateCapabilityTypes() {
  const catalog = await readJson('capabilities.json');
  const entries = [...catalog.capabilities].sort((a, b) => a.name.localeCompare(b.name));
  const edited = entries.find((entry) => entry.name === EDITED_CAPABILITY);
  if (!edited) {
    throw new Error(`capabilities.json has no ${EDITED_CAPABILITY}; re-export the snapshot`);
  }

  const names = entries.map((entry) => `  | ${JSON.stringify(entry.name)}`).join('\n');
  const meta = entries
    .map(
      (entry) =>
        `  ${JSON.stringify(entry.name)}: {\n` +
        `    permission: ${JSON.stringify(entry.permission)},\n` +
        `    humanOnly: ${entry.human_only},\n` +
        `    longRunning: ${entry.long_running},\n` +
        `    summary: ${JSON.stringify(entry.summary)},\n` +
        `    semantics: ${JSON.stringify(entry.scientific_semantics)},\n` +
        `  },`,
    )
    .join('\n');
  const planned = (catalog.planned ?? [])
    .map((item) => `  { name: ${JSON.stringify(item.name)}, reason: ${JSON.stringify(item.reason)} },`)
    .join('\n');

  const body = `${BANNER}

/** Every capability this build of the daemon exposes. A typo is a compile error. */
export type CapabilityName =
${names};

export interface CapabilityMeta {
  /** What the call is allowed to touch: read, stage, mutate, or admin. */
  permission: 'read' | 'stage' | 'mutate' | 'admin';
  /** True when the call needs the researcher; the cockpit disables it for an agent host. */
  humanOnly: boolean;
  /** True when the call returns a run id and finishes in the background. */
  longRunning: boolean;
  summary: string;
  semantics: string;
}

export const CAPABILITIES: Record<CapabilityName, CapabilityMeta> = {
${meta}
};

/** Product 22 names this build does not implement, with the reason it gives a host. */
export const PLANNED_CAPABILITIES: ReadonlyArray<{ name: string; reason: string }> = [
${planned}
];

/**
 * The \`${EDITED_CAPABILITY}\` request schema, as the daemon publishes it. The Evidence
 * editor validates a hand edit against its \`${EDITED_PROPERTY}\` property before posting;
 * the daemon validates it again and its refusal is what counts.
 */
export const EDIT_CANDIDATE_SCHEMA = ${JSON.stringify(edited.request_schema, null, 2)} as const;

/** The property of that request the hand-edited object goes in. */
export const EDIT_CANDIDATE_PROPERTY = ${JSON.stringify(EDITED_PROPERTY)};
`;
  await writeFile(resolve(out, 'capabilities.gen.ts'), body, 'utf8');
  return 'src/api/capabilities.gen.ts';
}

await mkdir(out, { recursive: true });
for (const written of await Promise.all([generateRouteTypes(), generateCapabilityTypes()])) {
  console.log(`  written  web/${written}`);
}
