"""Render `docs/guide/capabilities.md` from the capability registry itself.

Run it after adding or renaming a capability, and commit the output:

    uv run python docs/guide/gen_capabilities.py

The table is `CapabilityRegistry.describe()` — the same descriptors a host reads from
`GET /capabilities`, `research capabilities`, and every MCP tool's metadata — so the page
cannot claim a capability the build does not register (ADR-004).
"""

from __future__ import annotations

from pathlib import Path

# Imported for its side effect: the registry's optional handlers are imported lazily, and
# some of them sit on an import cycle that resolves only once the application packages are
# loaded. A real client (`research capabilities`, `research serve`, `research mcp`) has
# loaded them before it builds a registry; a bare script has not, and would record two
# working capabilities as "not built yet". `_refuse_local_paths` catches it if the
# difference ever reappears.
import research_harness.cli.app  # noqa: F401
from research_harness.capabilities.registry import CapabilityDescriptor, build_default_registry
from research_harness.protocol.mcp import mcp_tool_name

OUTPUT = Path(__file__).resolve().parent / "capabilities.md"

HEADER = """<!-- Generated by docs/guide/gen_capabilities.py. Do not edit by hand. -->

# Capabilities

A *capability* is a named operation with one implementation, reachable identically from
the CLI, the local HTTP daemon, an MCP host, the Web cockpit, and the VS Code extension
(ADR-004). The table below is generated from the registry, so it is exactly what this
build exposes. Regenerate with:

```bash
uv run python docs/guide/gen_capabilities.py
```

Print the same list from a workspace with `research capabilities` (add `--schemas` for
each capability's request and response JSON schema, or `--json` for the whole descriptor).

## Permissions

| permission | what it may touch |
|---|---|
| `read` | accepted state and the regenerable projection; writes nothing |
| `stage` | `.research/staging/` only — proposals a person still has to review |
| `mutate` | accepted scientific state |
| `admin` | rebuilds or initialises regenerable infrastructure |

Who holds them:

| principal | granted | how it is recognised |
|---|---|---|
| `human` | `read`, `stage`, `mutate`, `admin` | the CLI, and any caller with the daemon token |
| `agent_host` | `read`, `stage` | any MCP host, and an HTTP caller with no valid token |
| `model` | `read`, `stage` | an internal model worker (Product 21) |

`mutate` and `admin` additionally require a human principal whatever else was granted, so
an agent host that calls one gets `permission_denied` rather than a partial write. The
**human** column below marks capabilities that need the researcher; it is true for every
`mutate` and `admin` capability and for anything else flagged `human_only`.

## The table

**MCP tool** is the capability name with dots replaced by underscores, which is the whole
mapping — a host that has seen `claim.audit` in the catalog knows to call `claim_audit`.

"""

FOOTER_TEMPLATE = """
## Not built yet

These names exist in the product design but have no implementation in this build. Asking
for one returns "not built yet" rather than a stub that answers something plausible.

{planned}
"""


def row(descriptor: CapabilityDescriptor) -> str:
    human = "yes" if descriptor.human_only else ""
    long_running = " Returns a run id." if descriptor.long_running else ""
    return (
        f"| `{descriptor.name}` | `{mcp_tool_name(descriptor.name)}` | "
        f"`{descriptor.permission.value}` | {human} | "
        f"{descriptor.summary} {descriptor.scientific_semantics}.{long_running} |"
    )


def _refuse_local_paths(body: str) -> None:
    """A checked-in page must not record where it happened to be generated.

    A capability whose optional import failed is recorded as *planned* with the import
    error as its reason, and that error carries an absolute path. Writing it would commit
    one machine's filesystem into the docs and, worse, publish a transient failure as a
    permanent "not built yet". Fix the tree and run again.
    """
    here = str(Path.cwd().resolve())
    if here in body:
        raise SystemExit(
            f"refusing to write {OUTPUT}: the registry reported something naming {here}, "
            "which means a capability failed to import rather than being genuinely "
            "unimplemented. Fix the import and re-run."
        )


def main() -> None:
    registry = build_default_registry()
    lines = [
        "| capability | MCP tool | permission | human | what it does, and what it changes |",
        "|---|---|---|---|---|",
        *(row(descriptor) for descriptor in registry.describe()),
    ]
    planned = (
        "\n".join(f"* `{item.name}` — {item.reason}" for item in registry.planned()) or "* (none)"
    )
    body = HEADER + "\n".join(lines) + "\n" + FOOTER_TEMPLATE.format(planned=planned)
    _refuse_local_paths(body)
    OUTPUT.write_text(body, encoding="utf-8")
    print(f"wrote {OUTPUT} ({len(registry)} capabilities, {len(registry.planned())} planned)")


if __name__ == "__main__":
    main()
