"""Render `docs/guide/cli-reference.md` from the real Typer app.

Run it after changing any command, and commit the output:

    uv run python docs/guide/gen_cli_reference.py

Every block below is the command's own `--help`, captured through Typer's `CliRunner`
against `research_harness.cli.app.app`, so the reference cannot describe a flag the CLI
does not have. `COLUMNS` is pinned so the width does not depend on whose terminal ran it.
"""

from __future__ import annotations

import os
from collections.abc import Iterator
from pathlib import Path

WIDTH = "88"
os.environ["COLUMNS"] = WIDTH
os.environ["TERM"] = "dumb"

import click  # noqa: E402 - after COLUMNS, which Click reads at import time
from typer.main import get_command  # noqa: E402
from typer.testing import CliRunner  # noqa: E402

from research_harness.cli.app import app  # noqa: E402

OUTPUT = Path(__file__).resolve().parent / "cli-reference.md"

HEADER = """<!-- Generated by docs/guide/gen_cli_reference.py. Do not edit by hand. -->

# CLI reference

Every command of the `research` CLI, with its own `--help` text. Regenerate with:

```bash
uv run python docs/guide/gen_cli_reference.py
```

Two options recur and are not repeated in prose below:

* `--workspace` / `-w` — the workspace root. Without it a command reads
  `RESEARCH_WORKSPACE`, then walks up from the current directory looking for
  `research.yaml`.
* `--json` — print the result as JSON instead of text. The JSON is the scriptable
  interface; the text is for reading.

A command that fails prints one `error: ...` line on stderr and exits 1.
"""


def walk(path: list[str], command: click.Command) -> Iterator[list[str]]:
    """Every command path in the app, parents before children, alphabetical."""
    yield path
    children = getattr(command, "commands", None)
    if children:
        for name in sorted(children):
            yield from walk([*path, name], children[name])


def render(runner: CliRunner, path: list[str]) -> str:
    """One section: the invocation, then the command's own help output."""
    invocation = " ".join(["research", *path])
    result = runner.invoke(app, [*path, "--help"])
    if result.exit_code != 0:  # pragma: no cover - a broken command is a build failure
        raise SystemExit(f"`{invocation} --help` exited {result.exit_code}:\n{result.output}")
    heading = "#" * (2 + len(path)) if path else "##"
    body = "\n".join(line.rstrip() for line in result.output.splitlines()).rstrip()
    return f"{heading} `{invocation}`\n\n```text\n{body}\n```\n"


def main() -> None:
    runner = CliRunner()
    root = get_command(app)
    sections = [render(runner, path) for path in walk([], root)]
    OUTPUT.write_text(HEADER + "\n" + "\n".join(sections), encoding="utf-8")
    print(f"wrote {OUTPUT} ({len(sections)} commands)")


if __name__ == "__main__":
    main()
