"""The application capability layer: the only supported way to change accepted state.

`capabilities/` sits between the domain/workspace layers and every transport (ADR-004).
CLI, HTTP, MCP, Web, and VS Code all call the same handlers, so the review gate
(ADR-003, ADR-007), the journalled event (ADR-001), and dependency invalidation
(ADR-008) have exactly one enforcement point. Nothing here imports `cli/` or `server/`,
and nothing here imports a parser or a model provider.
"""

from __future__ import annotations

from research_harness.capabilities.context import (
    CapabilityContext,
    actor_provenance,
    open_context,
)
from research_harness.capabilities.diff import ChangeKind, SemanticDiff, semantic_diff
from research_harness.capabilities.dto import (
    AcceptDecisionRequest,
    AcceptEvidenceRequest,
    AddArtifactRequest,
    AddNoteRequest,
    AttachManuscriptAnchorRequest,
    AuditClaimRequest,
    CapabilityRequest,
    CreateClaimRequest,
    CreateQuestionRequest,
    IngestLocalPdfRequest,
    InitProjectRequest,
    InitProjectResult,
    MutationResult,
    OverrideClaimStrengthRequest,
    ParseWorkRequest,
    PromoteNoteRequest,
    PutMatrixRequest,
    PutTaxonomyRequest,
    RecordSearchRunRequest,
    RegisterWorkRequest,
    RejectEvidenceRequest,
    StoreParsedDocumentRequest,
    UpdateQuestionRequest,
    ValidationReport,
)
from research_harness.capabilities.handlers import (
    CAPABILITY_HANDLERS,
    PROJECT_INIT,
    accept_decision,
    accept_evidence,
    add_note,
    add_version_artifact,
    attach_manuscript_anchor,
    audit_claim,
    create_claim,
    create_question,
    ingest_local_pdf,
    init_project,
    override_claim_strength,
    parse_work,
    promote_note,
    put_matrix,
    put_taxonomy,
    record_search_run,
    register_work,
    reject_evidence,
    store_parsed_document,
    update_question,
)
from research_harness.capabilities.invalidation import (
    DependencyInvalidation,
    InvalidationHook,
    NullInvalidation,
)
from research_harness.capabilities.permissions import (
    AGENT_HOST_PERMISSIONS,
    HUMAN_PERMISSIONS,
    CapabilityNotFound,
    InvalidRequest,
    Permission,
    PermissionDenied,
    Principal,
    PrincipalKind,
)
from research_harness.capabilities.registry import (
    CapabilityDescriptor,
    CapabilityRegistry,
    CapabilitySpec,
    InitProjectResponse,
    MutationResponse,
    PlannedCapability,
    StaleBody,
    ValidationBody,
    build_default_registry,
)

__all__ = [
    "AGENT_HOST_PERMISSIONS",
    "CAPABILITY_HANDLERS",
    "HUMAN_PERMISSIONS",
    "PROJECT_INIT",
    "AcceptDecisionRequest",
    "AcceptEvidenceRequest",
    "AddArtifactRequest",
    "AddNoteRequest",
    "AttachManuscriptAnchorRequest",
    "AuditClaimRequest",
    "CapabilityContext",
    "CapabilityDescriptor",
    "CapabilityNotFound",
    "CapabilityRegistry",
    "CapabilityRequest",
    "CapabilitySpec",
    "ChangeKind",
    "CreateClaimRequest",
    "CreateQuestionRequest",
    "DependencyInvalidation",
    "IngestLocalPdfRequest",
    "InitProjectRequest",
    "InitProjectResponse",
    "InitProjectResult",
    "InvalidRequest",
    "InvalidationHook",
    "MutationResponse",
    "MutationResult",
    "NullInvalidation",
    "OverrideClaimStrengthRequest",
    "ParseWorkRequest",
    "Permission",
    "PermissionDenied",
    "PlannedCapability",
    "Principal",
    "PrincipalKind",
    "PromoteNoteRequest",
    "PutMatrixRequest",
    "PutTaxonomyRequest",
    "RecordSearchRunRequest",
    "RegisterWorkRequest",
    "RejectEvidenceRequest",
    "SemanticDiff",
    "StaleBody",
    "StoreParsedDocumentRequest",
    "UpdateQuestionRequest",
    "ValidationBody",
    "ValidationReport",
    "accept_decision",
    "accept_evidence",
    "actor_provenance",
    "add_note",
    "add_version_artifact",
    "attach_manuscript_anchor",
    "audit_claim",
    "build_default_registry",
    "create_claim",
    "create_question",
    "ingest_local_pdf",
    "init_project",
    "open_context",
    "override_claim_strength",
    "parse_work",
    "promote_note",
    "put_matrix",
    "put_taxonomy",
    "record_search_run",
    "register_work",
    "reject_evidence",
    "semantic_diff",
    "store_parsed_document",
    "update_question",
]
