import type { LucideIcon } from 'lucide-react';
import {
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  ArrowUpRight,
  AtSign,
  BookOpen,
  Bookmark,
  Bot,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  CircleAlert,
  CircleCheck,
  CircleDashed,
  CircleHelp,
  CircleX,
  Clock,
  CloudOff,
  Copy,
  CornerDownLeft,
  Download,
  Ellipsis,
  ExternalLink,
  Eye,
  EyeOff,
  File,
  FileText,
  Folder,
  FolderOpen,
  Funnel,
  Gavel,
  GitBranch,
  Globe,
  GripVertical,
  HardDrive,
  Hash,
  Image,
  Inbox,
  Info,
  Layers,
  Library,
  Link,
  Link2Off,
  List,
  Loader,
  Lock,
  Maximize,
  Menu,
  MessageSquare,
  MessagesSquare,
  Minus,
  Moon,
  PanelLeft,
  PanelRight,
  Paperclip,
  PenLine,
  Play,
  Plus,
  Quote,
  RefreshCw,
  RotateCcw,
  RotateCcwClock,
  Scale,
  Search,
  Send,
  Settings,
  ShieldOff,
  Sparkles,
  Square,
  Sun,
  Table,
  Tag,
  Trash2,
  TriangleAlert,
  User,
  WifiOff,
  Wrench,
  X,
  ZoomIn,
  ZoomOut,
} from 'lucide-react';
// manuscript and workspace icons (DS2b)
import {
  BookMarked,
  Columns2,
  Crosshair,
  FileCode,
  FilePlus,
  GitCompare,
  Microscope,
  PanelBottom,
  Rows2,
  Save,
  Shield,
} from 'lucide-react';

/**
 * The curated icon set.
 *
 * Icons are bundled with the package through `lucide-react`; nothing is fetched from a
 * CDN at runtime. Names are kebab-case and stable — they are the public API, so an
 * upstream rename is absorbed here rather than rippling through the product (lucide 1.x
 * renamed `AlertTriangle`, `AlertCircle`, `Filter`, `History` and `MoreHorizontal`).
 *
 * Keep this one line per icon so it stays append-friendly.
 */
export const icons = {
  'alert-circle': CircleAlert,
  'alert-triangle': TriangleAlert,
  'arrow-down': ArrowDown,
  'arrow-left': ArrowLeft,
  'arrow-right': ArrowRight,
  'arrow-up': ArrowUp,
  'at-sign': AtSign,
  'book-open': BookOpen,
  bookmark: Bookmark,
  check: Check,
  'chevron-down': ChevronDown,
  'chevron-right': ChevronRight,
  'circle-check': CircleCheck,
  'circle-dashed': CircleDashed,
  clock: Clock,
  copy: Copy,
  download: Download,
  'external-link': ExternalLink,
  eye: Eye,
  'eye-off': EyeOff,
  file: File,
  'file-text': FileText,
  filter: Funnel,
  folder: Folder,
  'folder-open': FolderOpen,
  'git-branch': GitBranch,
  hash: Hash,
  history: RotateCcwClock,
  image: Image,
  info: Info,
  link: Link,
  list: List,
  loader: Loader,
  lock: Lock,
  menu: Menu,
  minus: Minus,
  moon: Moon,
  'more-horizontal': Ellipsis,
  'panel-left': PanelLeft,
  'panel-right': PanelRight,
  paperclip: Paperclip,
  'pen-line': PenLine,
  play: Play,
  plus: Plus,
  quote: Quote,
  'refresh-cw': RefreshCw,
  'rotate-ccw': RotateCcw,
  search: Search,
  send: Send,
  settings: Settings,
  sparkles: Sparkles,
  square: Square,
  sun: Sun,
  table: Table,
  tag: Tag,
  'trash-2': Trash2,
  x: X,
  'zoom-in': ZoomIn,
  'zoom-out': ZoomOut,
  // overlay, navigation, and layout icons (DS1b) are appended below, one line each.
  'cloud-off': CloudOff,
  'grip-vertical': GripVertical,
  inbox: Inbox,
  'shield-off': ShieldOff,
  'wifi-off': WifiOff,
  // research semantics and conversation (DS2a), one line each.
  'arrow-up-right': ArrowUpRight,
  bot: Bot,
  'chevron-left': ChevronLeft,
  'chevron-up': ChevronUp,
  'circle-help': CircleHelp,
  'circle-x': CircleX,
  'corner-down-left': CornerDownLeft,
  gavel: Gavel,
  globe: Globe,
  'hard-drive': HardDrive,
  layers: Layers,
  library: Library,
  'link-2-off': Link2Off,
  maximize: Maximize,
  'message-square': MessageSquare,
  'messages-square': MessagesSquare,
  scale: Scale,
  user: User,
  wrench: Wrench,
  // manuscript and workspace composition (DS2b), one line each
  'book-marked': BookMarked,
  'columns-2': Columns2,
  crosshair: Crosshair,
  'file-code': FileCode,
  'file-plus': FilePlus,
  'git-compare': GitCompare,
  microscope: Microscope,
  'panel-bottom': PanelBottom,
  'rows-2': Rows2,
  save: Save,
  shield: Shield,
} satisfies Record<string, LucideIcon>;

/** Every name the registry answers to. */
export type IconName = keyof typeof icons;

/** Sorted list of registered names, for specimens and tests. */
export const ICON_NAMES: IconName[] = (Object.keys(icons) as IconName[]).sort();
